### ISSUE TITLE
[Question] I want to use some mixins of Falsetweaks in my mods 

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalseTweaks#101]
I marked my licence As General public licence, but what do you mean by the "SNEED" word

![Capture d’écran_2023-04-27_17-02-16](https://user-images.githubusercontent.com/42176772/234904326-101fe16b-3f5e-4fe5-8658-cf6f1e2737d1.png)

**Comment by FalsePattern** [comment]
[feed and seed](https://www.youtube.com/watch?v=T3ElIvNBYj0)
