### ISSUE TITLE
Water glitch in 2.4.0

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#103]
## FalseTweaks 2.4.0:

https://user-images.githubusercontent.com/122032896/235363387-b3f48ad0-089a-4c66-99a7-646a7a892c55.mp4

## FalseTweaks 2.3.1:

https://user-images.githubusercontent.com/122032896/235363442-76236e3c-1c41-4c9c-9620-ed934db7aa43.mp4

**Comment by Thaumatarge** [comment]
This affects more than just water, practically all transparent blocks have this issue, an example is Thaumcraft's warded jars.

False Tweaks 2.3.1
![2023-05-07_10 45 27](https://user-images.githubusercontent.com/34694089/236667457-28103e28-1831-4519-8b38-027c73859069.png)

False Tweaks 2.4.2
![2023-05-07_10 46 15](https://user-images.githubusercontent.com/34694089/236667482-aea9c673-e98e-45f8-afa8-eaa566e8852a.png)

**Comment by Darek505** [comment]
Fixed in 2.5.0+
