### ISSUE TITLE
[2.4.2] Thaumcraft's Warded Jars render wrong

### ISSUE THREAD

**Issue by Thaumatarge** [FalsePattern/FalseTweaks#105]
As I have noted in #103 and shared my experience with a similar bug to that report, the bug may not be of the same nature, and so I am making a new report instead.

In FalseTweaks **2.3.1** the jars render correctly
![2023-05-07_10 45 27](https://user-images.githubusercontent.com/34694089/236667763-af7a467d-239a-44b0-9c9a-64442b10aa93.png)

But in False Tweaks **2.4.2** the jars have this issue
![2023-05-07_10 46 15](https://user-images.githubusercontent.com/34694089/236667777-d51d220d-4445-462b-a3f3-24061fd449a2.png)

I imagine this has something to do with the vertex data API changes introduced in 2.4.0, but I am not completely sure about that.

**Comment by Darek505** [comment]
Should be fixed in 2.5.0+
![Base Profile Screenshot 2023 05 14 - 15 44 03 67](https://github.com/FalsePattern/FalseTweaks/assets/122032896/648b9188-fd9a-4f90-bddb-3165d9b5f2e0)

**Comment by Houstonruss** [comment]
This is working  /  fixed. 2.5.7
