### ISSUE TITLE
Broken water with shaders (2.5.1)

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#108]
At first when I saw this I thought that either the drivers were broken or the graphics card, but then I discovered that these "things" appear only in certain places, and so that was water

https://github.com/FalsePattern/FalseTweaks/assets/122032896/0fa0716f-5f99-41f9-898e-14fccbeacc7a

**Comment by FalsePattern** [comment]
Fixed in 2.5.2
