### ISSUE TITLE
Is this a client-only mod?

### ISSUE THREAD

**Issue by pavog** [FalsePattern/FalseTweaks#109]
From the description I assume that it is a client-only mod, am I right?
On https://modrinth.com/mod/falsetweaks it says: 
- Client: Optional
- Server: Optional 
- 
?!?

**Comment by FalsePattern** [comment]
Yes, most of the graphical features and optimizations are only for client side, for serverside optimizations on 1.7.10 you should check out ArchaicFix

**Comment by pavog** [comment]
Okay, thank you.
And why does it say "Client or server" on https://modrinth.com/mod/falsetweaks ?
