### ISSUE TITLE
crash with newest

### ISSUE THREAD

**Issue by iamsoNewBee** [FalsePattern/FalseTweaks#110]
[minecraft-exported-crash-info-2023-05-20T17-52-42.zip](https://github.com/FalsePattern/FalseTweaks/files/11522006/minecraft-exported-crash-info-2023-05-20T17-52-42.zip)

**Comment by FalsePattern** [comment]
Fixed in 2.5.3

**Comment by iamsoNewBee** [comment]
fixed.
