### ISSUE TITLE
TEXTURE_OPTIMIZATIONS striping issue

### ISSUE THREAD

**Issue by DarianLStephens** [FalsePattern/FalseTweaks#112]
I'm not sure if this is a mod interaction or what, but with specifically this option enabled, I see this:
![2023-05-21_15 22 26](https://github.com/FalsePattern/FalseTweaks/assets/15375876/fceaf3a5-28fc-4f2a-8b3f-c72d4c21bf2f)
When I turn it off, it's normal:
![2023-05-21_15 23 53](https://github.com/FalsePattern/FalseTweaks/assets/15375876/949b7608-5895-427b-a1fe-918b4a257450)

**Comment by DarianLStephens** [comment]
Seems to happen with most any mod installed.
Tested with Botania and Thaumcraft separately, and Botania made the Gravel have the lines, while Thaumcraft + Botania made Sand have the lines.
The weirdness makes me suspect something bigger is going on, unrelated to the actual mods, so for now I'll just leave that option off despite of the performance it brings, same with the Item Voxellizer problem reported in my other issue.

**Comment by DarianLStephens** [comment]
That's the weird thing, though... I _do_ have Anisotropic Filtering disabled!
And it doesn't show up with FalseTweaks itself, or even vanilla, I need to add some other mods to the mix.

**Comment by DarianLStephens** [comment]
Proof or something:
![2023-05-23_22 21 52](https://github.com/FalsePattern/FalseTweaks/assets/15375876/50d193cb-684c-4a31-8bc6-b29947c717f8)
![2023-05-23_22 21 54](https://github.com/FalsePattern/FalseTweaks/assets/15375876/7c6bb515-c9ae-44c4-b789-01e9cb5ee12d)

**Comment by FalsePattern** [comment]
Does it also happen with mipmaps set to 0?

**Comment by DarianLStephens** [comment]
Nope, but _man_ does the game look bad:
![2023-05-23_22 24 02](https://github.com/FalsePattern/FalseTweaks/assets/15375876/007d071a-dd45-4173-8a4a-d47d18a8e137)
![2023-05-23_22 24 19](https://github.com/FalsePattern/FalseTweaks/assets/15375876/7045c5ca-771b-411d-8184-738f6899861e)

I've also only seen Anisotropic Filtering cause problems with animated textures, never static. This is a new thing.
Though it would be nice if AF could be fixed, because it does make stuff look a lot better. I live without because of the water thing, but if it could... I dunno, ignore water and other animated textures, at least? It would be appreciated.

**Comment by DarianLStephens** [comment]
For the heck of it, I also loaded up Vanilla 1.7.10 to test Anisotropic Filtering, and the incorrect color-change is there, too!
![2023-05-23_22 31 11](https://github.com/FalsePattern/FalseTweaks/assets/15375876/cba1991a-6522-43f4-866b-86b59f827784)
But it's only visible on higher render distances, which explains why I never noticed it before since I used to always play on 8.

**Comment by AxolotlAccount** [comment]
Disabling MIPMAP_FIX from falsetweaks.cfg and disabling Anisotrophic Filtering from OptiFine options fixed the issue for me.

**Comment by DarianLStephens** [comment]
Wait, this is actually fixed now?

**Comment by Omgise** [comment]
@FalsePattern Could this issue be fixed in FalseTweaks 4.0?
