### ISSUE TITLE
ArchaicFix - enableThreadedChunkUpdates + Item Voxellizer Strangeness

### ISSUE THREAD

**Issue by DarianLStephens** [FalsePattern/FalseTweaks#113]
Wasn't sure where to post this, so just referencing the issue from the ArchaicFix repo:
https://github.com/embeddedt/ArchaicFix/issues/94

The short version is: With both options enabled, items seem to randomly flicker between other items or blocks, usually non-solid or animated blocks, like grass, vines, and fire.

**Comment by FalsePattern** [comment]
Fixed in 3.x
