### ISSUE TITLE
Chromaticraft Cave Crystals rendering

### ISSUE THREAD

**Issue by Rimusp** [FalsePattern/FalseTweaks#115]
With the newest version of Falsetweaks(2.5.3) Chromaticrafts Cave Crystals have a weird rendering bug.
Looks normal with 2.3.1 and versions between either crash my game or have other graphical bugs.
other performance mods i use are archaic fix and neodymium no optifine used.

how it looks with 2.5.3
![2023-06-03_15 31 16](https://github.com/FalsePattern/FalseTweaks/assets/111206050/c8169d1f-4735-42a9-9224-b38314f9d445)

and with 2.3.1

![2023-06-03_15 38 34](https://github.com/FalsePattern/FalseTweaks/assets/111206050/5d5e165f-33f0-481b-b840-6cdd89326df1)

**Comment by brandyyn** [comment]
thank you for reporting this, i was about to report this too. same thing happens with jewellerycraft crystals. 

here's a pic of chromaticraft crystals and jewellerycraft crystals
![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/606439f6-f9be-4a07-8fea-61aea23ce023)

![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/b50fc6d4-4d2c-434d-9b30-7d178b106e41)

**Comment by brandyyn** [comment]
@FalsePattern I know you are a busy man but this has been a problem for so long now so maybe a little nudge will help :0

**Comment by FalsePattern** [comment]
Should be fixed in 2.6.1

**Comment by brandyyn** [comment]
> Should be fixed in 2.6.1

it is fixed, you can close this

**Comment by Rimusp** [comment]
just tested and yes its fixed
