### ISSUE TITLE
Video memory leak on AMD Video card

### ISSUE THREAD

**Issue by Serega007RU** [FalsePattern/FalseTweaks#119]
Everything is shown in the video
https://www.youtube.com/watch?v=PfCe2xAsUyA

More detailed explanations:
In order not to delay the video, I put the video on 2 pauses, at the beginning to demonstrate an increase in memory consumption and at the end when the memory is almost exhausted

Why did I decide that this is only for AMD graphics cards? I have 3 other friends, one has a GTX 550 TI graphics card and he does not have such a problem. The rest of my two friends have a graphics card from AMD and they have such a problem. If you need the exact models of these video cards, I can provide.

What does FalseTweaks have to do with it? Without FalseTweaks, this problem does not occur, but at least on vanilla modpack without other mods. On modpack with a bunch of popular mods, there is still a memory leak, as I understand it, but at least it is not as aggressive as with FalseTweaks. Maybe this is really a problem specifically for AMD, it's hard for me to understand what's wrong with AMD.

I hope for your help in studying this problem, write for any additional information

I'm sorry that the interface is in Russian, I myself am Russian and it's difficult for me to switch to English to demonstrate the bug.

Versions:
Forge 1.7.10 10.13.4.1614
UniMixins-all 0.1.11
FalsePatternLib 0.11.4
FalseTweaks 2.5.5
AMD Driver 23.5.2 Stable version

Save of world [test.zip](https://github.com/FalsePattern/FalseTweaks/files/11931178/test.zip)

**Comment by FalsePattern** [comment]
FalseTweaks has a workaround for 22.X versions of AMD drivers that used to stop a memory leak with minecraft.
It looks like in newer versions of the drivers, it behaves a lot differently and actually worsens the leak.

I removed the automatic detection code from the bugfix, and made it Disabled by default in 2.5.6, so the leak should no longer happen now.

**Comment by Serega007RU** [comment]
Yes, it looks like this is an AMD drivers problem, but I found a workaround for myself.

Oddly enough, but https://github.com/makamys/Neodymium/ solves this problem
