### ISSUE TITLE
Crash with ShadersModCore mod when Triangulator of 00_modules in config file is open.

### ISSUE THREAD

**Issue by XLin0mu** [FalsePattern/FalseTweaks#122]
ShadersModCore  v2.3.31f
falsetweaks v2.5.7
log:
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/12367807/latest.log)

**Comment by FalsePattern** [comment]
Standalone shadersmod is unsupported, try with OptiFine.

**Comment by Xlin0mu** [comment]
But this ShadersModCore can work normally without OptiFine.
And when item triangulator's value is false, it works well too.

**Comment by FalsePattern** [comment]
> But this ShadersModCore can work normally without OptiFine. And when item triangulator's value is false, it works well too.

Triangulator's compatibility was designed based on OptiFine's version of shadersmod, which is a backport of the minecraft 1.8 shadersmod, and has different code in it.

**Comment by Xlin0mu** [comment]
yes. I mean, you could put this into your README.md as a notice.
