### ISSUE TITLE
Crash- Comparison method violates its general contract!

### ISSUE THREAD

**Issue by DomobotX** [FalsePattern/FalseTweaks#123]
Been having an issue recently where after 10-20 minutes, the game will hitch, blank out, and crash. I'm not 100% sure what the cause is but this didn't come up until I started using more than a few Thaumcraft (and Automagy) mirrors. Time might not be a factor as much as the number of items going through the mirrors? Like I said, I'm not sure.
[crash-2023-08-31_22.11.31-client.txt](https://github.com/FalsePattern/FalseTweaks/files/12492280/crash-2023-08-31_22.11.31-client.txt)

Edit: After some experimentation I don't think it was the mirrors doing it, but rather the number of TC jars I had in one area (4x48, ha...)

**Comment by FalsePattern** [comment]
You can work around this by going into `falsetweaks.cfg` in your configs, and under the `00_modules` category, set `TE_TRANSPARENCY_FIX` to `false`

**Comment by DomobotX** [comment]
That did the trick, thank you!
