### ISSUE TITLE
[1.7.10]NoClassDefFoundError: net/minecraft/client/renderer/Tessellator

### ISSUE THREAD

**Issue by ptk2003** [FalsePattern/FalseTweaks#124]
forge:1.7.10-10.13.4.1614
+unimixins-all-1.7.10-0.1.11 (with 00gasstation-mc1.7.10-0.5.1 same)
falsetweaks-mc1.7.10-2.6.1
[crash-2023-09-06_14.47.20-client.txt](https://github.com/FalsePattern/FalseTweaks/files/12536938/crash-2023-09-06_14.47.20-client.txt)

**Comment by FalsePattern** [comment]
Seems like a collision with another mod in your modpack. Try removing other mods one by one until it no longer happens to pinpoint exactly which mod it's incompatible with.
