### ISSUE TITLE
Crashes on Startup, possibly conflict between Falsetweaks and Hodgepodge?

### ISSUE THREAD

**Issue by toErIpNid** [FalsePattern/FalseTweaks#128]
Log: https://hastebin.skyra.pw/fosufikeca.md

Was recommended to make an issue here in case it's on False's end.

**Comment by Darek505** [comment]
ModContainerFactory - this means it is related to loading mods in forge.
Disable startup_optimizations in the falsetweaks config
 (.minecraft\config\falsetweaks.cfg -> 00_modules -> B:STARTUP_OPTIMIZATIONS=false)
 Should help
