### ISSUE TITLE
Injection validation failed: Constant modifier method extendDrawOffset(I)I

### ISSUE THREAD

**Issue by iocmet** [FalsePattern/FalseTweaks#129]
For some reason tesselator mixin not loads with this error:
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Constant modifier method extendDrawOffset(I)I in mixins.falsetweaks.json:client.triangulator.TessellatorMixin expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap mixins.falsetweaks.refmap.json [INJECT Applicator Phase -> mixins.falsetweaks.json:client.triangulator.TessellatorMixin -> Apply Injections ->  -> PostInject -> mixins.falsetweaks.json:client.triangulator.TessellatorMixin->@ModifyConstant::extendDrawOffset(I)I]`
I maximally reduced mod list and here is it
![image](https://github.com/FalsePattern/FalseTweaks/assets/63492966/4b95058b-0b4a-4f80-a5ec-12f6614133d0)
(Patcher is mixin loader compatible with GasStation)
I also tried use GasStation and ran into same error
UPD: I gets this error even only with mixin loader, falsepatternlib, falsetweaks and optifine

**Comment by FalsePattern** [comment]
Remove -Dmixin.debug=true for the time being
