### ISSUE TITLE
Incorrect water rendering if optifine shaders enabled

### ISSUE THREAD

**Issue by iocmet** [FalsePattern/FalseTweaks#130]
![image](https://github.com/FalsePattern/FalseTweaks/assets/63492966/bef36f10-d4ca-4703-ad62-8cbb874c508f)
Used shader https://legacy.curseforge.com/minecraft/shaders/bsl-shaders/files/4799242
Version 2.6.2

**Comment by FalsePattern** [comment]
Try disabling quad triangulation in the settings gui.

**Comment by FalsePattern** [comment]
Should be fixed in 3.x
