### ISSUE TITLE
Item flickering when sprint-flying.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalseTweaks#131]
Title. A Dropbox link for a video is provided since GitHub's file size limit is 100 MB.

https://www.dropbox.com/scl/fi/karqoknea2vd3jppmmo38/javaw_kl8Fi1MnYV.mp4?rlkey=087t34kaivbt676ff5femboyx&dl=0

Some items flicker more, others less.

**Comment by FalsePattern** [comment]
Turn off the voxelizer module.

**Comment by FalsePattern** [comment]
Should be fixed in 3.x
