### ISSUE TITLE
Terrain is invisible with Threading chunk Update

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalseTweaks#132]
Modpack : 

Biggess Pack Cat Edition V0.88 DEV

![image](https://github.com/FalsePattern/FalseTweaks/assets/42176772/b97cace3-d6ad-4ee4-ac08-2a925fed75e9)

logs : 

[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/13415176/fml-client-latest.log)

**Comment by quentin452** [comment]
The bug also appear with only Falsetweaks + Falsepatternlib + GasStation installed

**Comment by brandyyn** [comment]
> Not compatible with the ArchaicFix's occlusion culling for obvious reasons. You need to turn off that one first.
> Not compatible with the FastCraft's culling tweaks. However, this module is a direct replacement for it, so if you enable this module with FastCraft present, it will automatically replace the FastCraft culling tweaks without any manual changes needed.

**Comment by FalsePattern** [comment]
Duplicate of #134 ?

**Comment by FalsePattern** [comment]
Should be fixed in preview 3

**Comment by quentin452** [comment]
Nop wasn't duplicated of #134 ,but its fixed thx
