### ISSUE TITLE
Multithreaded chunk rendering causes the chunk to "flicker" sometimes

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#133]
Sorry that the video lags, I just don’t know how to configure obs correctly, I can also say that this happens without shaders/optifine

https://github.com/FalsePattern/FalseTweaks/assets/122032896/451d9103-a231-4529-902e-b5e5e7911715

**Comment by FalsePattern** [comment]
Migrated issue to #142
