### ISSUE TITLE
new chunk update bugs 

### ISSUE THREAD

**Issue by brandyyn** [FalsePattern/FalseTweaks#137]
![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/9c2f4ca6-fc5e-4b3a-90b8-36868113df4f)

grass sides appear to be fast rendering with the new chunk update & i'm getting chunks glitching in and out in my view and chunk holes. im using chunk update threads on 0 (which is 8 for my system) (edit, still happens with it set to 1) 
also my hand / item glitches every few seconds (disabling item voxelizer seems to fix this)

chunks do seem to render very fast though 

https://github.com/FalsePattern/FalseTweaks/assets/11356565/23136f33-facb-4c26-bf87-faab381fa324

![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/6c393b18-0245-41c9-9e3c-47d69703159a)

list of mods:
https://pastebin.com/L57iUEyU

**Comment by brandyyn** [comment]
https://github.com/FalsePattern/FalseTweaks/assets/11356565/51276e11-91cb-4713-a7a4-4c70b72b45dd

**Comment by FalsePattern** [comment]
Migrated issue to #142
