### ISSUE TITLE
chunks are not rendered, with optifine zoom

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#138]
https://github.com/FalsePattern/FalseTweaks/assets/122032896/f273ef29-4587-4bcf-a441-b6dc02adc7fd

+, for some reason, some areas don't want to be rendered:

![2023-11-20_18 59 54](https://github.com/FalsePattern/FalseTweaks/assets/122032896/0a37bd98-4c5d-47ed-98c6-8900d4b4a95e)

(also 6 report related to Multithreaded chunk rendering/occlusion engine)

**Comment by Darek505** [comment]
another example of an area that is not rendering:

https://github.com/FalsePattern/FalseTweaks/assets/122032896/d3252dfc-6344-4cfd-bec9-d1f07db078eb



 (This is not a tps/cwg problem, it is just not rendering)

**Comment by quentin452** [comment]
does this version fix the problem? https://mega.nz/file/up0RUZyK#GcNB7D3PTuDG0MVdfCIzdIDyPvYEbC6Zq93V9gtfAmY

**Comment by Darek505** [comment]
> does this version fix the problem? https://mega.nz/file/up0RUZyK#GcNB7D3PTuDG0MVdfCIzdIDyPvYEbC6Zq93V9gtfAmY

it seems like no

**Comment by FalsePattern** [comment]
Does F3 + A fix it?

**Comment by Darek505** [comment]
> Does F3 + A fix it?

no, even breaking/placing blocks doesn't load these places

**Comment by FalsePattern** [comment]
Try removing all mods except optifine+mixins+fplib+falsetweaks, and see if the bug is still reproducible.

**Comment by Darek505** [comment]
### Zoom issue:
 I tried unimixins + falsetweaks 2.7.0 preview 1 (or 2, there is no difference), falsepatternlib 1.0.0 pre 0.2 and optifine (E7). Render distance - 16, to record the fragment below, I used `/tp ~ 300 ~` (and yes, I fixed obs):


https://github.com/FalsePattern/FalseTweaks/assets/122032896/9a0d9920-b253-4325-8e78-b5463f4b35dd

and also, I forgot to say, but you need to zoom not under yourself, but + - at the border of the render distance (or teleport to 500-600 Y, and set the render distance to 27-30, in this case, you can see it even not at the border of the chunks )



### Some places are not rendered:
same thing, falsetweaks (+ deps) and optifine, error present

**Comment by FalsePattern** [comment]
The bug with the chunks not rendering when above y=256 and looking in shallow angles is a known issue, but should not affect anything during survival play. Just stay under y=256 for now

**Comment by FalsePattern** [comment]
Fixed in preview 3

**Comment by Darek505** [comment]
tested preview 3, can confirm that the problem is solved, thank you!
