### ISSUE TITLE
Flickering snow at high Y (roughly 300-400) with occlusion tweaks & White octagon? (with shaders) on high Y (548 on 16 chunks)

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#139]
(snow) With shaders : https://www.veed.io/view/0e56d2dc-4240-49a5-9043-5231a58b9288?panel=share
(snow) Without shaders : https://www.veed.io/view/e5f2ed45-9f18-4b71-82c4-72b53df0b39c?sharingWidget=true&panel=share

"White octagon" with shaders : 
![2023-11-20_22 09 31](https://github.com/FalsePattern/FalseTweaks/assets/122032896/49b8698a-1e50-4a6f-b6b3-7411400b5bde)

**Comment by FalsePattern** [comment]
OpenGL rounding errors.

**Comment by Darek505** [comment]
(I understand that you are talking about “White octagon”?) ok, but can this be fixed? or is it something unfixable?

**Comment by FalsePattern** [comment]
Unfortunately not fixable, it's a known optifine shaders bug

**Comment by Darek505** [comment]
thanks for the info, but what about the snow problem?

**Comment by FalsePattern** [comment]
Again, OpenGL rounding errors.

**Comment by Darek505** [comment]
ah, that is, the problem with snow is also not fixable, right? If so, then perhaps we should close this issue?

**Comment by Darek505** [comment]
By the way, I really didn’t notice that vanilla has a problem with snow, I thought it was caused by occlusion tweaks from falsetweaks, but this error exists even without mods
