### ISSUE TITLE
"Weird white lines" with render distance >=45

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#143]
`B:SKY_MESH_OPTIMIZATION=true` fixes a problem with optifine shaders at a render distance >=27, in preview 3 it became possible to increase the render distance to 64, as a result of which, at a render distance >= 45, these "Weird white lines" appear again
  ( I apologize in advance if the function is not yet completed, and this is an unnecessary report of an unfinished function )
![2023-11-22_00 13 13](https://github.com/FalsePattern/FalseTweaks/assets/122032896/fa06d2be-be69-40dd-86f5-92f6ab65c6fd)

**Comment by FalsePattern** [comment]
Oh, i actually forgot to fix this one, good catch!
Fixed planned for the next preview

**Comment by FalsePattern** [comment]
Fixed in 2.7.0, make sure you enable the `SKY_MESH_OPTIMIZATION` module in the config (enabled by default)
