### ISSUE TITLE
Crash with hodgepodge

### ISSUE THREAD

**Issue by xronin01** [FalsePattern/FalseTweaks#147]
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/13464201/latest.log)

**Comment by Darek505** [comment]
1) hodgepodge is not supported on this end
2) Fixed by installing optifine or if you set `B:optimizeTextureLoading=false` in hodgepodge.cfg

**Comment by FalsePattern** [comment]
Fixed in latest dev commit, will be released in preview 5

**Comment by FalsePattern** [comment]
Released in 2.7.0
