### ISSUE TITLE
crash when trying to launch 2.7.1

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#150]
https://pastebin.com/1v6eajHU

**Comment by DarianLStephens** [comment]
Same here.
I've tried removing all mods besides FalsePatternLib, FalseTweaks, and Unimixins, and deleting the old configs, but the same 'no RenderBlocks class' crash.

**Comment by FalsePattern** [comment]
Fixed in 2.7.1 hotfix 1, make sure you also update FalsePatternLib to 1.0.0.
