### ISSUE TITLE
grass sides still fast texture

### ISSUE THREAD

**Issue by brandyyn** [FalsePattern/FalseTweaks#152]
![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/4593eb2c-6ae7-42c1-9279-54969ea685a3)

**Comment by brandyyn** [comment]
doesn't happen when i turn off THREADED_CHUNK_UPDATES, and possibly DISABLE_BLOCKING_CHUNK_UPDATES? (i disabled them both at the same time)

![image](https://github.com/FalsePattern/FalseTweaks/assets/11356565/1cb6b8f3-c619-4566-a0d1-3fbc55eebf74)

**Comment by FalsePattern** [comment]
Please bisect your modpack and figure out which mod this conflicts with, i can't reproduce this in a clean instance with only mixins + fplib + falsetweaks

**Comment by FalsePattern** [comment]
Duplicate of #145.
