### ISSUE TITLE
Can't enter the world in my modpack

### ISSUE THREAD

**Issue by M3MEMonster** [FalsePattern/FalseTweaks#153]
The game can startup normally, but when I try to create/enter a world,it will remind me"Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive" and I can't enter the world. That happened in my modpack which contains fastcraft1.25+optifine E7+coretweaks+bugtorch+foamfix+Neodymium and a lot of other mods.

**Comment by brandyyn** [comment]
do you have the latest version of falsepatternlib?

**Comment by M3MEMonster** [comment]
falsepatternlib-1.0.0
Oh,I used an old version of unimixins!
I've updated it and I'm starting game to try it again.

**Comment by M3MEMonster** [comment]
Ah!It solved!
