### ISSUE TITLE
[2.7.3] Crashing on startup with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by TheUnderTaker11** [FalsePattern/FalseTweaks#156]
Full crash report
[crash-2023-12-15_17.12.37-client.txt](https://github.com/FalsePattern/FalseTweaks/files/13690319/crash-2023-12-15_17.12.37-client.txt)

Mod list
[ModList.txt](https://github.com/FalsePattern/FalseTweaks/files/13690329/ModList.txt)

Relevant config file entries (as per common fixes):
B:STARTUP_OPTIMIZATIONS=false
B:MIPMAP_FIX=false
B:TE_TRANSPARENCY_FIX=false
B:RENDER_HOOK_COMPAT_MODE=true

A few more lines from latest log that might be useful
[17:12:37] [Client thread/INFO] [shadersmod.common.SMCLog]: [Shaders] No shaderpack loaded.
[17:12:37] [Thread-8/INFO] [Config]: [OptiFine] Version found: E7
[17:12:37] [Chunk Worker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[17:12:37] [Chunk Worker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.falsepattern.falsetweaks.modules.occlusion.ChunkThread.run(ChunkThread.java:50)

Note: I do NOT have shadersmod , it's not in my mods folder and not in my mods list, so not sure what that output in the client log is.

**Comment by FalsePattern** [comment]
Seems like a weird internal bug in mixins. I'll add a workaround in the next release.

**Comment by aking4125** [comment]
Getting the same issue with 2.8.1

[crash-2024-01-13_15.11.14-client.txt](https://github.com/FalsePattern/FalseTweaks/files/13929413/crash-2024-01-13_15.11.14-client.txt)

**Comment by FalsePattern** [comment]
Remove other mods one by one and try again, figure out exactly which one of your mods it conflicts with, and then post the results here.

**Comment by aking4125** [comment]
BetterFPS is the conflicting mod.

**Comment by brandyyn** [comment]
> BetterFPS is the conflicting mod.

@roadhog360

**Comment by Roadhog360** [comment]
Are you pinging me because I don't think BetterFPS should be used in any context?

Anyways, BetterFPS should not be used in any context

**Comment by brandyyn** [comment]
> Are you pinging me because I don't think BetterFPS should be used in any context?
> 
> Anyways, BetterFPS should not be used in any context

More ammo for your minigun

**Comment by WolfBV** [comment]
@aking4125 Change the algorithm in betterfps.txt to either rivens, rivens-full, libgdx, java, or vanilla.
