### ISSUE TITLE
Block holes with OF+FTw

### ISSUE THREAD

**Issue by AnrDaemon** [FalsePattern/FalseTweaks#157]
Both blocks are ~regular wooden planks, no different than the rest on the floor~ EnderIO-painted Glowstone.
The issue is consistent across relogs and persist without OF.

![2023-12-24_21 46 24](https://github.com/FalsePattern/FalseTweaks/assets/6532485/d4d77a60-87be-42b1-a70c-e50ecedeac14)
![2023-12-25_12 25 32](https://github.com/FalsePattern/FalseTweaks/assets/6532485/0fb53da2-acf6-4be3-a92a-2ea96d432019)
![2023-12-25_13 27 32](https://github.com/FalsePattern/FalseTweaks/assets/6532485/3854bf01-90ba-40a8-9657-f59aed83e759)

A short list of mods:

EnderIO-2.8.4.jar (GTNH fork, but reproducible with stock one)
falsepatternlib-mc1.7.10-1.2.3.jar
falsetweaks-mc1.7.10-2.8.1.jar

**Comment by FalsePattern** [comment]
Does it happen without the XRay mod?

**Comment by AnrDaemon** [comment]
Yes. It happens in any combination provided FTw is installed. Even if it installed alone. I can't think of anything specific with these specific tiles, there's no light emitters in these places (the roof is just wooden slabs, all the light is from two skull candles, one you can see and another further back and to the left), there's not even anything of interest directly under these tiles.

**Comment by AnrDaemon** [comment]
Mystery solved! 😊 
It is an EnderIO-painted glowstone. It wasn't showing itself with yeta wrench, so I assumed there's no trickery. But actually breaking it yielded the block with suspiciously recognizable markings… so, yeah. /blush

**Comment by AnrDaemon** [comment]
Will test at weekend.

**Comment by AnrDaemon** [comment]
Quick test seems to be fine
![2024-12-08_21 28 23](https://github.com/user-attachments/assets/cc5d5d26-b982-449c-9802-a82c23cf6a40)
ms to be fine
