### ISSUE TITLE
Crash with AF 0.7.0. Its Threaded Updates have been removed.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalseTweaks#161]
Title.

[crash-2024-01-05_16.57.31-client.txt](https://github.com/FalsePattern/FalseTweaks/files/13847723/crash-2024-01-05_16.57.31-client.txt)
[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/13847724/fml-client-latest.log)

![image](https://github.com/FalsePattern/FalseTweaks/assets/51277766/169f2e69-5972-4915-9f2f-20d11f348abc)

**Comment by MagmaBro123** [comment]
@FalsePattern Still happening. Is the old AF version ever gonna be updated?

**Comment by FalsePattern** [comment]
This crash is impossible in 3.0.0, the offending code has been removed from FalseTweaks

**Comment by MagmaBro123** [comment]
Ah. Didn't know you fixed this. This should've been closed when Beta 1 was out.
