### ISSUE TITLE
[2.8.1] Crash on startup: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Dante-0-5** [FalsePattern/FalseTweaks#162]
Crash Report: 
[crash-2024-01-27_12.22.24-client.txt](https://github.com/FalsePattern/FalseTweaks/files/14072068/crash-2024-01-27_12.22.24-client.txt)
Modlist: 
[Modlist.txt](https://github.com/FalsePattern/FalseTweaks/files/14072069/Modlist.txt)

Getting a crash on startup which looks quite similar to issue #156, but still seems distinct. In my case, the error is "cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer".

I followed the fixes for common problems in the readme, and even with every fix applied, the game crashes. 

I've done some experimenting, and I managed to narrow the error down to Neodymium. Removing it fixes the crash. Since the readme mentioned occlusion culling as a source of errors with ArchaicFix, I disabled all culling options I could find in Neodymium, but to no avail. If required, I can run some more experiments around this problem. Cheers!

**Comment by mindbound** [comment]
Removing Neodymium didn't fix this error for me.

**Comment by FalsePattern** [comment]
Does this still happen on 3.0.0 beta 4 with my custom neodymium branch?
