### ISSUE TITLE
Crash with Chunk Pregenerator

### ISSUE THREAD

**Issue by brandyyn** [FalsePattern/FalseTweaks#170]
doesn't crash until i add chunk pregenerator 

[crash-2024-04-04_15.30.14-client.txt](https://github.com/FalsePattern/FalseTweaks/files/14872810/crash-2024-04-04_15.30.14-client.txt)
[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/14872811/fml-client-latest.log)

**Comment by FalsePattern** [comment]
Does this still happen in 3.5.x?

**Comment by brandyyn** [comment]
> Does this still happen in 3.5.x?

iirc it started working at some point, however i had other crashes with that chunk pregenerator mod unrelated to falsetweaks
