### ISSUE TITLE
the game keeps crashing with the hodgepodge mod

### ISSUE THREAD

**Issue by xronin01** [FalsePattern/FalseTweaks#171]
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/14949349/latest.log)

**Comment by FalsePattern** [comment]
Disable `fixPreserveQuadOrder` in hodgepodge config.

**Comment by xronin01** [comment]
When using GTNH-nei with FalseTweaks and hodgepodge, the game crashes even with fixPreserveQuadOrder disabled.

**Comment by xronin01** [comment]
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/15030010/latest.log)

**Comment by couleurm** [comment]
whats hodgepodge

**Comment by xronin01** [comment]
https://github.com/GTNewHorizons/Hodgepodge

**Comment by xronin01** [comment]
Will this be fixed?

**Comment by FalsePattern** [comment]
> [latest.log](https://github.com/FalsePattern/FalseTweaks/files/15030010/latest.log)

Disable `STARTUP_OPTIMIZATIONS` in the FalseTweaks config. It will be disabled by default in the next update, as it just causes this exact same crash in most modpacks.
