### ISSUE TITLE
Crash with techgun

### ISSUE THREAD

**Issue by svovl** [FalsePattern/FalseTweaks#172]
If OCLUSION_TWEAKS is true, it crashes when destroying chests (Reinforced_Chest, Weapon_Chest) that are added by techgun.
If I disable it, there is a slight performance problem and I am not sure whether to adjust the chest to unavailable.

[crash-2024-04-23_20.33.56-client.txt](https://github.com/FalsePattern/FalseTweaks/files/15084240/crash-2024-04-23_20.33.56-client.txt)

**Comment by FalsePattern** [comment]
Fixed in my local development repo, an update will be pushed this summer once i'm done with some IRL obligations.

**Comment by svovl** [comment]
I understand. Thank you for your prompt response.

**Comment by svovl** [comment]
I have checked the fix in 3.0.0 or later.


Is it within the specification that only when `THREADED_CHUNK_UPDATES` is `true`, it crashes as before?
And this may be a different problem, but it seems that some ores in GregTech are not rendered under the same conditions.

**Comment by FalsePattern** [comment]
Should be fixed in 3.5.x
