### ISSUE TITLE
[3.0.0] Fences in LotR mod are invisible

### ISSUE THREAD

**Issue by Anglo-Saxon-Elf** [FalsePattern/FalseTweaks#173]
All fence types from the LotR mod fail to render with FalseTweaks, including the oak fence which I believe is a rename of the vanilla Minecraft fence.

Upon removing LotR, vanilla Minecraft fence renders as normal, even with all other mods enabled.

Upon removing FalseTweaks, LotR fences can render, even with all other mods enabled.

![2024-04-29_20 51 08](https://github.com/FalsePattern/FalseTweaks/assets/90004358/d8228e62-50b2-4798-81a1-8d4c19bafbe4)

Modlist:
- [Born in a Barn](https://modrinth.com/mod/WfPGKC8F) [t2p54yVF]
- [BugTorch](https://modrinth.com/mod/6su8A6OH) [1.2.13]
- [FalsePatternLib](https://modrinth.com/mod/eGLBEILf) [1.1.0]
- [The Lord of the Rings Mod](https://www.curseforge.com/projects/423748) [Update 36.15]
- [BetterFps](https://www.curseforge.com/projects/229876) [1.0.1]
- [ArchaicFix](https://modrinth.com/mod/xTJanN3v) [0.7.2]
- [Damage Tilt](https://www.curseforge.com/projects/411705) [1.7.10-0.1.0]
- [ASMC](https://modrinth.com/mod/Xc1brHiM) [ocJww0CQ]
- [UniMixins](https://modrinth.com/mod/ghjoiQAl) [0.1.17]
- [Opinionation](https://www.curseforge.com/projects/846463) [1.0]
- [FoamFix](https://modrinth.com/mod/jupr7Bf5) [1.0.4]
- LOTR_UpdatedLangFiles
- [FalseTweaks](https://modrinth.com/mod/VTGi3upD) [3.0.0-beta0001]
- [LOTR Pouch Viewer](https://modrinth.com/mod/gxfUYjJR) [2.4.3]
- [Custom Main Menu](https://www.curseforge.com/projects/226406) [1.9.2]

**Comment by FalsePattern** [comment]
Start the game, place one of these buggy fences, then exit the game, and post your `fml_client_latest.log` file from `.minecraft/logs`

**Comment by Anglo-Saxon-Elf** [comment]
Pasted it [here](https://pastebin.ai/4ocvk9obex) as it was long. Please let me know if I can help further. Thanks.

**Comment by Anglo-Saxon-Elf** [comment]
Apologies for the delay, no, it appears to be working with the latest version (3.8.3). Thanks.
