### ISSUE TITLE
Need more details for proper instalation

### ISSUE THREAD

**Issue by Biskupsky** [FalsePattern/FalseTweaks#175]
I've installed 00gasstation 0.5.1 version, installed falsepatternlib 1.1.0 and FalseTweaks 3.0.0
When I delete falsepatternlib it shows this mod is missing, but when I put file into mods, game shuts down in a second. What proper files do I need to put in mods or maybe to put somewhere else ?

**Comment by Omgise** [comment]
You should use FalseTweaks+Falsepatternlib+UniMixins

**Comment by FalsePattern** [comment]
GasStation is deprecated, I've updated the readme.
