### ISSUE TITLE
Some chunks dont render, I have like 1 milion ping (cannot teleport, use eq etc)

### ISSUE THREAD

**Issue by Biskupsky** [FalsePattern/FalseTweaks#176]
Some chunks just stoped rendering and gamed freezed, cannot teleport etc like it has milion ping..... Mods for optimalization I used:
neodymium, falsetweaks, falsepatternlib, unimixins all

**Comment by Biskupsky** [comment]
> _No description provided._

**Comment by FalsePattern** [comment]
Should be fixed in 3.0.0 Beta 4
