### ISSUE TITLE
Block placing/breaking creates temp. ghost blocks.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalseTweaks#177]
Title.

GitHub hates files larger then 10 MB.
https://www.dropbox.com/scl/fi/hifw6g018s8v462hyxotw/javaw_OiT07IDPI0.mp4?rlkey=9qpyjmna0d3cyat3jet8hvzjj&st=z1kvwrx1&dl=0

Seems to be caused by your 3.0.0 Beta 1+ updates.

**Comment by FalsePattern** [comment]
Should be fixed in 3.0.0 Beta 4

**Comment by MagmaBro123** [comment]
This seems to still happen in Beta 4,, but its rare.

**Comment by FalsePattern** [comment]
It's a side effect of reducing the stuttering, instead of the game freezing until the chunk you changed finishes re-rendering, it just displays the old mesh until the worker thread finishes rendering the new mesh.

IMO a small delay in mesh updates is always preferrable to a stuttery mess
