### ISSUE TITLE
Incompat with chunkpregenerator

### ISSUE THREAD

**Issue by Speiger** [FalsePattern/FalseTweaks#178]
o/ Chunk Pregenerator dev here.

I am getting bugreports that false tweaks is causing issues with Chunk Pregenerator.
Reason being that i use their AtlasStitcher to make my own atlas, and your optimization basically selfdestructs itself when doing so.
Which most likely happens because you only expect one instance to be present.
This can be easily solved by assuming multiple "Stitcher" instances could exist.

Here is the relevant report.
If you need any extra info I am willing to provide all info you need.

https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/issues/63

Thank you for reading.
Speiger

**Comment by FalsePattern** [comment]
Should be fixed in 3.0.0 Beta 4

**Comment by Speiger** [comment]
@FalsePattern thank you for the quick response.
I will let the person know and let them try.

**Comment by FalsePattern** [comment]
Fixed, user forgot to delete AnimFix from the modpack.
