### ISSUE TITLE
Lighting underwater is very buggy.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalseTweaks#179]
Not sure if this is caused by Lumina or Tweaks, but lighting is very buggy underwater.

![2024-05-18_20 46 55](https://github.com/FalsePattern/FalseTweaks/assets/51277766/48062474-b87a-4689-aaa0-566f0df09f70)

Happens with or without other mods (besides Lumina and FalseTweaks).

**Comment by FalsePattern** [comment]
does this happen without FalseTweaks too?

**Comment by MagmaBro123** [comment]
Yes, seems to be a Lumina issue.

![2024-05-25_14 30 19](https://github.com/FalsePattern/FalseTweaks/assets/51277766/2f8c4dc2-bb55-463a-8844-1f360e7afde3)

**Comment by MagmaBro123** [comment]
On RC-9:

![2024-05-25_14 30 19](https://github.com/FalsePattern/FalseTweaks/assets/51277766/3a6c2cbc-757a-431d-8442-0c77b8635c77)

**Comment by MagmaBro123** [comment]
On rc9:

![2024-05-25_14 27 58](https://github.com/FalsePattern/FalseTweaks/assets/51277766/998c632a-8d6d-4d60-b285-cb5e3003a59e)

**Comment by FalsePattern** [comment]
Was that world ever opened using RPLE?

The underwater corals are designed to have a colored glow on them with that mod, but removing RPLE breaks it like this.

**Comment by MagmaBro123** [comment]
I never used RPLE.
