### ISSUE TITLE
[Notfine] Game crashes when THREADED_CHUNK_UPDATES is enabled

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/FalseTweaks#181]
[fml-client-latest.log](https://github.com/user-attachments/files/15750420/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/15750421/fml-junk-earlystartup.log)
[latest.log](https://github.com/user-attachments/files/15750422/latest.log)

**Comment by FalsePattern** [comment]
Threaded updates are not compatible with Notfine. Use Optifine instead, FalseTweaks has compatibility patches for it.

**Comment by brandyyn** [comment]
turn off faceculling in notfine configs @Omgise
