### ISSUE TITLE
When THREADED_CHUNK_UPDATES is enabled, the game crashes if GTNH Lib is installed

### ISSUE THREAD

**Issue by Guy-that-exists** [FalsePattern/FalseTweaks#190]
[fml-client-latest.log](https://github.com/user-attachments/files/16653943/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/16653944/fml-junk-earlystartup.log)
[latest.log](https://github.com/user-attachments/files/16653945/latest.log)

**Comment by FalsePattern** [comment]
This is caused by GTNHLib merging in features that should belong in Angelica (see: https://github.com/GTNewHorizons/GTNHLib/pull/49)

I've fixed it in dev, the fix will be available in the next falsetweaks update

**Comment by FalsePattern** [comment]
Moved to https://github.com/GTNewHorizons/GTNHLib/issues/53
