### ISSUE TITLE
Weird rendering overlay 

### ISSUE THREAD

**Issue by tempoletion** [FalsePattern/FalseTweaks#192]
Gregtech 6 block had a weird rendering position

![IMG_20240906_102149.jpg](https://github.com/user-attachments/assets/6d5f1073-2cb7-4a55-8aff-d2e9dcbcecaf)

![IMG_20240906_102203.jpg](https://github.com/user-attachments/assets/ed9de298-9a94-45ec-b12f-dd4241768ac8)

![IMG_20240906_102219.jpg](https://github.com/user-attachments/assets/41eced70-266e-464a-a182-cd7a34becc57)

**Comment by tempoletion** [comment]
##Mod list:

#false tweak

- Falsetweak 3.1.1
- Falsepatternlib 1.4.0
- unimixin 0.1.17

#optimizing mod

- Optifine  D6
- Coretweak 0.3.3.2
- fastleafdecay
- FpsReducer
- modspawnfix
- mob no render
- born in a barn
- entityculling 1.6.4

#other mod

- Gregtech 6
- gt6 nei ore plugin
- gt6 ore helper
- Prospect Journal
- JourneyMap 5.2.5
- Sampler 1.60.1
- Waila 1.8.1
- Waila harvestability 1.1.6
- Wawla 1.0.5.120

**Comment by tempoletion** [comment]
##Mod list:

#false tweak

- Falsetweak 3.1.1
- Falsepatternlib 1.4.0
- unimixin 0.1.17

#optimizing mod

- Optifine  D6
- Coretweak 0.3.3.2
- fastleafdecay
- FpsReducer
- modspawnfix
- mob no render
- born in a barn
- entityculling 1.6.4

#other mod

- Gregtech 6
- gt6 nei ore plugin
- gt6 ore helper
- Prospect Journal
- JourneyMap 5.2.5
- Sampler 1.60.1
- Waila 1.8.1
- Waila harvestability 1.1.6
- Wawla 1.0.5.120

**Comment by FalsePattern** [comment]
Should be fixed in 3.1.2
