### ISSUE TITLE
[bug] Triangulator calibration message writes command into chat

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalseTweaks#193]
Title.

falsetweaks-mc1.7.10-3.1.1.

![2024-09-28_03 39 09](https://github.com/user-attachments/assets/7c4e0510-421e-424a-a22e-be1b36063b90)

Tested with and without other mods, same result.

**Comment by FalsePattern** [comment]
Does it just write in chat when you click the message?

**Comment by MagmaBro123** [comment]
Yes.

**Comment by FalsePattern** [comment]
Doesn't happen for me in a test instance with only falsetweaks and its dependencies

**Comment by MagmaBro123** [comment]
It seems this is caused by GTNHLib and Hodgepodge (I doubt you will fix this since I know you and GTNH aren't exactly friends).
