### ISSUE TITLE
Crash when enable or change shaders in game runtime with neodymium installed

### ISSUE THREAD

**Issue by huihiuhuai** [FalsePattern/FalseTweaks#194]

**Comment by huihiuhuai** [comment]
[crash-2024-09-30_22.37.55-client.txt](https://github.com/user-attachments/files/17192485/crash-2024-09-30_22.37.55-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/17192486/fml-client-latest.log)

**Comment by huihiuhuai** [comment]
solved by disabling neodymium cullfaces

**Comment by huihiuhuai** [comment]
it happens with FT plus Nd with threaded chunk updates and neodymium integration disabled. 
if threaded chunk updates and neodymium integration are enabled, the crash wont happen but every time i change shaders my fps stuttered hard.

**Comment by FalsePattern** [comment]
Try removing every mod except `Unimixins, FalsePatternLib, FalseTweaks, Neodymium, Optifine`, maybe it's some other mod causing it.
Also, which shaders are you using?

**Comment by huihiuhuai** [comment]
Ziipzaaps shaders

**Comment by huihiuhuai** [comment]
id love to try if can reproduce it, but it will be this next weekend  (┬＿┬)

**Comment by FalsePattern** [comment]
That is fine, no need to hurry.

**Comment by huihiuhuai** [comment]
crash report with the minimum installation
[crash-2024-12-08_12.23.10-client.txt](https://github.com/user-attachments/files/18050734/crash-2024-12-08_12.23.10-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/18050737/fml-client-latest.log)

**Comment by huihiuhuai** [comment]
hello I sent the new crash report

**Comment by FalsePattern** [comment]
Fixed in NeodymiumUnofficial 0.4.1
