### ISSUE TITLE
Crash when installed alongside Angelica

### ISSUE THREAD

**Issue by vizthex123** [FalsePattern/FalseTweaks#196]
Very odd crash, but I finally narrowed it down to this mod.

Log:
[latest.log](https://github.com/user-attachments/files/17689806/latest.log)

Forge log if it helps:
[fml-client-latest.log](https://github.com/user-attachments/files/17689807/fml-client-latest.log)

Running v3.3.0 of the mod and v1.4.4 of the library. Didn't try downgrading either of them to see if it helped.

**Comment by FalsePattern** [comment]
FalseTweaks is not compatible with Angelica.

**Comment by vizthex123** [comment]
> FalseTweaks is not compatible with Angelica, use [Neodymium](https://github.com/FalsePattern/NeodymiumUnofficial) instead of Angelica.

which one's better overall? Can't really find anything about it.

**Comment by FalsePattern** [comment]
> > FalseTweaks is not compatible with Angelica, use [Neodymium](https://github.com/FalsePattern/NeodymiumUnofficial) instead of Angelica.
> 
> which one's better overall? Can't really find anything about it.

It depends. With Angelica you get higher maximum FPS, but FalseTweaks+Neodymium has stabler frametimes and a little bit less microstuttering when well configured, and FalseTweaks also ships with default settings that are more compatible with old mods.

**Comment by FalsePattern** [comment]
Also, falsetweaks is fully compatible with optifine, so you can have stuff like connected textures, shaders, etc. (basically whatever optifine supports)

**Comment by vizthex123** [comment]
alright, guess i'll have to test it out then. Thanks.
