### ISSUE TITLE
Weird dynamic hand lights when shaders are on

### ISSUE THREAD

**Issue by huihiuhuai** [FalsePattern/FalseTweaks#199]
remove Neodymium or disable threaded chunk updates supresses this bug
![image](https://github.com/user-attachments/assets/17989d95-eacf-4b89-bea5-33cdc8240a12)
[fml-client-latest.log](https://github.com/user-attachments/files/17788686/fml-client-latest.log)

https://github.com/user-attachments/assets/e297e5f3-c7c0-44b2-a5ee-190ae1053a98

**Comment by FalsePattern** [comment]
Fixed in 3.5.0
