### ISSUE TITLE
Crash with malisis doors with threaded updates enabled

### ISSUE THREAD

**Issue by huihiuhuai** [FalsePattern/FalseTweaks#202]
[crash-2024-11-24_12.16.09-client.txt](https://github.com/user-attachments/files/17891758/crash-2024-11-24_12.16.09-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/17891759/fml-client-latest.log)

**Comment by huihiuhuai** [comment]
[fml-client-latest.log](https://github.com/user-attachments/files/17891785/fml-client-latest.log)
[crash-2024-11-24_12.31.29-client.txt](https://github.com/user-attachments/files/17891786/crash-2024-11-24_12.31.29-client.txt)

**Comment by huihiuhuai** [comment]
i installed FalseTweaks3.5.1, Neodymium0.4.0, Malisis Doors GTNH 1.17.4/Malisis Doors 1.13.2. The game crash when i place doors that have animations such as rusty ladder door

**Comment by huihiuhuai** [comment]
i use config for FT, Nd, Malisis Doors from MEGA but it doesnt help resolve the crash

**Comment by huihiuhuai** [comment]
The crash happens with both original Malisis Doors and GTNH fork of Malisis Doors

**Comment by brandyyn** [comment]
same issue here, i crash when i place down a rusty ladder from malisis doors
[crash-2024-11-26_18.09.37-client.txt](https://github.com/user-attachments/files/17967662/crash-2024-11-26_18.09.37-client.txt)

![image](https://github.com/user-attachments/assets/661721ad-b7f3-4cdd-b939-8557118323b0)
