### ISSUE TITLE
Multithreaded chunk update mode crashes with carpenter's blocks

### ISSUE THREAD

**Issue by AgentAlpha81** [FalsePattern/FalseTweaks#203]
[crash-2024-11-28_00.03.42-client.txt](https://github.com/user-attachments/files/17939109/crash-2024-11-28_00.03.42-client.txt)

**Comment by FalsePattern** [comment]
Use this fork of Carpenter's Blocks: https://github.com/GTMEGA/carpentersblocks/releases/tag/3.4.1-mega
