### ISSUE TITLE
3.7.1 crash with no crash report

### ISSUE THREAD

**Issue by huihiuhuai** [FalsePattern/FalseTweaks#204]
[fml-client-latest.log](https://github.com/user-attachments/files/18046298/fml-client-latest.log)

**Comment by huihiuhuai** [comment]
i have only False Tweaks、FPLib、Unimixins installed

**Comment by FalsePattern** [comment]
Should be fixed in 3.7.2

**Comment by huihiuhuai** [comment]
confirmed no crash
