### ISSUE TITLE
[Compatibility Request]: Water has a weird rendering under water with TFC+

### ISSUE THREAD

**Issue by Jerome226** [FalsePattern/FalseTweaks#22]
### Other mod's name

TerraFirmaCraft+

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/terrafirmacraftplus

### Other mod's license

GPLv3

### Game log

too big and probably not needed in this case

### Description

Water on blocks like ice produce some weird triangle on block faces.
![image](https://user-images.githubusercontent.com/55724525/174920665-32a6be4c-fe02-4fbd-b9ee-3b31ecdbb395.png)

### Existing Patches

- [X] This request is not for OptiFine
- [X] This request is not for FoamFix
- [X] This request is not for RedstonePaste

**Comment by facetorched** [comment]
#13 mentions that this is fixed, but I just checked again today (on a different computer) with version 1.7.1 of triangulator and it seems like this issue has been re-introduced.

Perhaps it was never fixed and I simply made a mistake last time.

**Comment by FalsePattern** [comment]
I've looked into this a bit further, it seems like TerraFirmaCraft's ice renderer itself has a Z-fighting issue with its water.
It needs to be fixed on their side, in the meantime, you can set `ENABLE_QUAD_TRIANGULATION` to false in `triangulator.cfg`, and it will use the fallback algorithm instead, which is way more compatible with buggy mods

**Comment by FalsePattern** [comment]
yep, exactly that

**Comment by FalsePattern** [comment]
moved to #25
