### ISSUE TITLE
Translucent Blocks render issue with liquids

### ISSUE THREAD

**Issue by facetorched** [FalsePattern/FalseTweaks#25]
![image](https://user-images.githubusercontent.com/60113330/177248643-4bec1f65-0fdc-4a8c-b4e1-ebe04de031e3.png)

#22 shows an identical render issue but it was assumed it was an issue with TFC+. I just loaded triangulators with vanilla minecraft and it seems like minecraft ice and stained glass have this rendering issue with water.

**Comment by FalsePattern** [comment]
This is a known vanilla bug: [MC-91224](https://bugs.mojang.com/browse/MC-91224).
I will look into fixing this in the future, but for now it's low priority.

**Comment by FalsePattern** [comment]
Added a workaround in 2.0 Alpha 3. The Z fighting is still present, but now it's consistent across the entire quads, so it's not that visible.

**Comment by FalsePattern** [comment]
(cc #22)

**Comment by FalsePattern** [comment]
@facetorched any updates?

**Comment by facetorched** [comment]
Yes it seems to be fixed after upgrading to falsetweaks-mc1.7.10-2.0.0-alpha0005, falsepatternlib-mc1.7.10-0.10.11, 00gasstation-mc1.7.10-0.3.5

Had to remove archaicfix from my mods folder for it to launch though. Haven't had the time to test exactly what the cause and if I do i will open an issue.
