### ISSUE TITLE
Lines between blocks (also known as MC-1794)

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#31]
Hello, I know this has nothing to do with your mod, however I have seen other people asking to fix bugs in the original game so I recently encountered bug MC-1794 and can't fix it so I would like this one the mod could do this, I don’t know if it’s possible.
![2022-09-02_18 23 14](https://user-images.githubusercontent.com/110309314/188190935-8710e48e-7cf5-49e7-97dc-e1177423da33.png)
![2022-09-02_16 55 50](https://user-images.githubusercontent.com/110309314/188191029-24f93eda-30fb-4bfa-90b7-7574d8a0e65d.png)
![2022-09-02_13 17 59](https://user-images.githubusercontent.com/110309314/188191120-88184562-cac2-47da-9d52-274ebe5c7c27.png)
![2022-09-02_16 07 59](https://user-images.githubusercontent.com/110309314/188284181-b4a52708-b49e-461e-9502-8ce64b4d5cfa.png)
![2022-09-02_18 23 13_2](https://user-images.githubusercontent.com/110309314/188284185-b285d70a-6dd5-4045-ac00-cd2f124d1c5b.png)
![bsl 2](https://user-images.githubusercontent.com/110309314/188284186-064ec349-e0d3-423e-b37e-6d5776c49a86.png)
![bsl 7 1 4 1](https://user-images.githubusercontent.com/110309314/188284187-61eed524-5622-41de-a5d5-ede67baa902e.png)
![bsl](https://user-images.githubusercontent.com/110309314/188284188-76dbbd4d-8714-4888-92b1-cc0882395c61.png)

**Comment by SirFell** [comment]
Try optifine's/shadermod's supersampling (or play around with your GPU's antialiasing, which is the likeliest cause of this anyway)

**Comment by kotmatross28729** [comment]
> 



> Try optifine's/shadermod's supersampling (or play around with your GPU's antialiasing, which is the likeliest cause of this anyway) Also if you have NVIDIA GPU consider trying to update graphics drivers to latest


I tried all of this, searched all Internet, nothing helps, I have already updated the drivers 10 times at latest version from geforce experience, reinstalled both optifine, client, and java, did everything possible in the nvidia panel, absolutely nothing helps.

**Comment by kotmatross28729** [comment]
> Try optifine's/shadermod's supersampling (or play around with your GPU's antialiasing, which is the likeliest cause of this anyway) Also if you have NVIDIA GPU consider trying to update graphics drivers to latest

It only worked if fast render is enabled, but shaders don't work with it, and for some reason some resource packs are no longer displayed in the selection menu (the first time I see this at all)

**Comment by kotmatross28729** [comment]
Just checked and noticed a strange feature, These lines in vanilla (without shaders and optifine) are only in 1.7.10, and starting from 1.8 only with shaders (no matter what), but in 1.8 and later they are less noticeable (still there) and in 1.7.10 themes it becomes impossible to play with shaders anymore (if you go into a cave, or a gorge between mountains)
Because there are everywhere these flickering lines of small dots through which you can see the lava.
I can’t say for sure, but maybe in 1.8 the system for rendering the corners of polygons was changed?
Although with shaders it is still present
By the way, this problem happened to me not so recently (5-6 months ago)
And either it somehow fixed itself (perhaps with a driver update), or I just didn’t notice, because I didn’t go through the caves, but now I’m building an assembly for 1.7.10 and this thing haunts me, because it terribly infuriates me
as I said none of the ways work in my case, tried all the ways on https://bugs.mojang.com/browse/MC-1794 but none fixed this problem

**Comment by FalsePattern** [comment]
Should be fixed in 2.0 alpha 1

**Comment by kotmatross28729** [comment]
> Should be fixed in 2.0 alpha 1


"Mixin config mixins.triangulator.json requires mixin subsystem version 0.8.3 but 0.7.11 was found. The mixin config will not be applied."

What does it mean?
Everything seems to be set up correctly.

**Comment by kotmatross28729** [comment]
Yes, the mod does not help.
Can this be taken into account because it's only an alpha version?
I have been looking for a solution to this problem for 5 months, and it has been with me since the year before last

**Comment by kotmatross28729** [comment]
I don’t know why, I want to whine and cry again here, hmm, hmm, sorry
version : 2.0.0-alpha0001



Here you can see that there are cracks on objects
(because it's harder to take screenshots on blocks, so there is a video)
Vanilla bow and bow from mod
![bow crack](https://user-images.githubusercontent.com/110309314/192034188-f76c4a0f-d118-4ab3-b625-fff74dc25421.png)
![modded bow crack](https://user-images.githubusercontent.com/110309314/192034720-a88a9f67-e46e-489d-a495-3b275285ebb2.png)

And here are 2 videos that show more scary things.
These small dots are also cracks, only they are all over the object

https://user-images.githubusercontent.com/110309314/192034972-fe8a845c-f33d-4ae6-b6b5-c72bd8e79d9c.mp4

https://user-images.githubusercontent.com/110309314/192035052-2fdbc1d4-fde2-4bd9-87cc-31d34cc0dfee.mp4


Why shaders?
Because you can see it better with them (well, I like to play with them)

And of course blocks...

https://user-images.githubusercontent.com/110309314/192036217-2a4a1478-e5c6-444f-b17a-76db6fac76fc.mp4

And it also does not depend on shaders, as I already wrote.
here is vanilla

https://user-images.githubusercontent.com/110309314/192036397-c1b41c19-6a19-4684-a26f-4c79822735b3.mp4

**Comment by FalsePattern** [comment]
For the item cracks, i have a potential solution in the works on the [voxelizer](https://github.com/FalsePattern/FalseTweaks/tree/voxelizer) branch.

For the block cracks, i'll need to tweak it a bit more so that the correction is a bit more intense at chunk borders.

**Comment by kotmatross28729** [comment]
> For the item cracks, i have a potential solution in the works on the [voxelizer](https://github.com/FalsePattern/FalseTweaks/tree/voxelizer) branch (not ingame yet, just raw experimental code).
> 
> For the block cracks, i'll need to tweak it a bit more so that the correction is a bit more intense at chunk borders.


Hmm, in that case, does it mean that it is still fixable?
I can notice, nevertheless, the mod slightly reduces the number of cracks on the blocks

**Comment by FalsePattern** [comment]
Could you check if both of these crack types still happen on 2.0 Alpha 3 on your system. They should be fixed properly now.

The block crack fix is now tunable in the config, because every gpu needs a slightly smaller/larger value for fixing it.

**Comment by kotmatross28729** [comment]
> Could you check if both of these crack types still happen on 2.0 Alpha 3 on your system? They should be fixed properly now.
> 
> The block crack fix is now tunable in the config, because every gpu needs a slightly smaller/larger value for fixing it.


In vanilla, it doesn't seem to be visible on items, but I can't check for sure, the shaders don't work and give the same error (it just crashes if I use 3 alpha)

**Comment by kotmatross28729** [comment]
## WONDERFUL JOB

## Before:

https://user-images.githubusercontent.com/110309314/192145751-69b300f4-723b-475e-9c71-f5db088a89ec.mp4

https://user-images.githubusercontent.com/110309314/192145756-d6ee0d19-abb1-4ce4-80e9-703893f1b2b2.mp4


 ## After:

https://user-images.githubusercontent.com/110309314/192145820-592d1818-bfdc-4c70-bcdc-33482bd17a50.mp4


https://user-images.githubusercontent.com/110309314/192145822-e7f5e903-c32b-4d53-bbfc-33541c0e0187.mp4

## And about the cracks in the blocks.
I turned the DOF and Motion blur up to absurd values, and they are not visible.
No, maybe they are and they flicker, but not at all significantly (and certainly not as it was before - flickering with huge crosses, from which I wanted to break the monitor)
Well, or I'm blind, although even so, I can't see them


## But some issues:


https://user-images.githubusercontent.com/110309314/192146091-00e3ce75-4c85-4400-8557-20648ec8dca9.mp4

this is due to the resource pack that adds reflections.
For some reason, immeno the sea lantern starts using the texture of reflections differently than others.
I can assume that this is because of the animation in the center
![issue texture](https://user-images.githubusercontent.com/110309314/192146437-fc6d55e4-f607-4346-a886-19e95ed9aa1f.png)

Namely, on his animation on the "texture of reflections"
so, others have only one "frame" and he has several.
This was not in alpha 1, but you can probably solve it if you remove the "frames" in the animation of this block


This is what they look like normally
![image](https://user-images.githubusercontent.com/110309314/192146273-f2c4fd4f-71bb-4ed6-a9ad-209b2a02efff.png)
![image](https://user-images.githubusercontent.com/110309314/192146520-09d6ef84-b950-4f95-8817-dda112aa83ca.png)


Well, on some items, "Z-fighting" remained (By the way, this may be the fault of the author of the mod, so you may not have anything to do with this at all. Because there is no such thing on spawn eggs, leather armor and the rest, only on things from this mod)

https://user-images.githubusercontent.com/110309314/192146751-7c562053-fdab-4bd0-9b4c-64a663c08c2a.mp4

Well, all the same, the enchantment remains

https://user-images.githubusercontent.com/110309314/192146862-5438d997-a4a4-41ff-a174-e65c88f443d5.mp4

(What's with the skin, lol, et futurum is a genius)



## **BUT**
alpha 4 made me VERY pleased, for which I am VERY grateful to you
