### ISSUE TITLE
Crash using FalseTweaks mod

### ISSUE THREAD

**Issue by OMGICE** [FalsePattern/FalseTweaks#38]
[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/9640083/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/FalsePattern/FalseTweaks/files/9640084/fml-junk-earlystartup.log)
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/9640085/latest.log)

**Comment by quentin452** [comment]
try updating gas station

**Comment by quentin452** [comment]
can you give me the mod list

**Comment by quentin452** [comment]
and give me working latest.log , i can't see it

**Comment by quentin452** [comment]
try deleting endlessid , seem to be incompatible with et futurum requiem https://github.com/FalsePattern/EndlessIDs/issues/39

> > and give me working latest.log , i can't see it
> 
> Because it's empty, you can't see it 😂

ah ok

**Comment by quentin452** [comment]
i found in my side a crash with cofh core and falsetweak

**Comment by iamsoNewBee** [comment]
> 我发现我这边发生了 cofh core 和 falsetweak 的崩溃（就像你的日志中一样的崩溃）

I MET IT TOO.MAYBE WE SHOULD REPORT THIS ISSUE.

**Comment by FalsePattern** [comment]
Closing this issue, the bug will be tracked in #39
