### ISSUE TITLE
Crash when using falsetweaks and cofhcore

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalseTweaks#39]
mods list : 

00gasstation-mc1.7.10-0.3.4
CoFHCore-[1.7.10]3.1.4-329
falsepatternlib-mc1.7.10-0.10.10
falsetweaks-mc1.7.10-2.0.0-alpha0003

logs : 

[latest.log](https://github.com/FalsePattern/FalseTweaks/files/9640173/latest.log)

**Comment by quentin452** [comment]
Probably the same issue like #38

**Comment by FalsePattern** [comment]
Disable the startup optimizations module (inside `falsetweaks.cfg`, set the `B:STARTUP_OPTIMIZATIONS` value to `false` under the `modules` category.

**Comment by quentin452** [comment]
ok

**Comment by quentin452** [comment]
fixed in [2.0.0-alpha0005](https://github.com/FalsePattern/FalseTweaks/releases/tag/2.0.0-alpha0005)
