### ISSUE TITLE
Z-fighting on spawn eggs and potions (and lether armor)

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#41]
Bruh, 2 issue today
in short z-fighting on spawn eggs and potions and lether armor

https://user-images.githubusercontent.com/110309314/192137821-7cd317fa-679b-42bd-9500-4e539b724356.mp4

https://user-images.githubusercontent.com/110309314/192138176-74296d56-f812-41dd-aeb4-ed3c4fbbe1a7.mp4

https://user-images.githubusercontent.com/110309314/192138264-148b23e8-ea43-4ce5-94de-691e676f70e0.mp4

**Comment by FalsePattern** [comment]
Fixed in 2.0 Alpha 4
