### ISSUE TITLE
vanishing quartz with pbr resource pack

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#42]
with false tweaks

https://user-images.githubusercontent.com/110309314/192160380-7883db5c-f075-4127-bcdc-a72e0729415f.mp4

without false tweaks

https://user-images.githubusercontent.com/110309314/192160391-132bb3d3-508f-416d-a07b-5134df9f7b9c.mp4

**Comment by kotmatross28729** [comment]
In the hand it appears transparent
![image](https://user-images.githubusercontent.com/110309314/192290341-763e0a89-f0fc-4e18-9e64-4b9d7a86e6dc.png)

**Comment by FalsePattern** [comment]
Please upload the specific shader pack zip you're using, along with your optifine version.

**Comment by kotmatross28729** [comment]
> Please upload the specific shader pack zip you're using, along with your optifine version.

[BSL_v8.1.03.15d.zip](https://github.com/FalsePattern/FalseTweaks/files/9677885/BSL_v8.1.03.15d.zip) <-------- Shaderpack
[§5AVPBR-1.7.zip](https://github.com/FalsePattern/FalseTweaks/files/9677887/5AVPBR-1.7.zip) <-------- this is the pbr texture pack that has the problem
Optifine HD U E7

**Comment by FalsePattern** [comment]
Ah, i see it now, the quartz in the texture pack has partially-transparent pixels. This will be fixed in alpha 5.

The issue was that the item voxelizer currently ignores any pixels that are not completely opaque. That was an incorrect assumption on my side.

**Comment by kotmatross28729** [comment]
yes thanks, now it works as expected
