### ISSUE TITLE
 cracks in the rails? (cracks on blocks 2?)  no, it's more of a question of how to use "it"

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#43]
Well, I even installed 3060 ti and the situation is this.
In the game, it seems that at first glance there is no, but if you poke your eyes at the monitor, you can notice small flashing dots.
So, on rails, this thing works to its fullest, especially with motion blur and DOF and open sun.
the question is,

general {
    # The "epsilon" value for the block crack fix inside chunks.
    # advanced setting.
    # FPS impact: None
    # [range: 0.0 ~ 0.005, default: 5.0E-4]
   ### D:BLOCK_CRACK_FIX_EPSILON=**0.001** <-------    what is this

I would like to know how to use this, i.e. I changed the value a bit, but I don't know what exactly this value does, the "smoothing" strength on the edges of the blocks?

https://user-images.githubusercontent.com/110309314/192615207-740cab85-b131-4edf-8190-d318e8cea3f8.mp4

**Comment by FalsePattern** [comment]
The epsilon value amplifies the vertex correction used for fixing the flickering on chunk boundaries.

The bug with 3d rails is a different issue due to how they're being rendered currently. You can set the graphics to fast to revert to flat rails, i will add a config option in the next release for toggling it, and also fix how they get rendered.

**Comment by kotmatross28729** [comment]
hmm, I think you still need to adjust quite a bit at the edges and it will be perfect (what you have already done deserves great praise)

https://user-images.githubusercontent.com/110309314/193280344-6b9da20a-4ff4-44aa-acfb-86940a087012.mp4

**Comment by FalsePattern** [comment]
The flickering should be gone in the latest release

**Comment by kotmatross28729** [comment]
> The flickering should be completely gone in the latest release now


yes, it seems to be working now, thanks!
