### ISSUE TITLE
Incompatible with Tinkers' Construct mod

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/FalseTweaks#44]
When I use the Concentrated Essence Berry, the game crashes.
[crash-2022-09-28_19.23.54-client.txt](https://github.com/FalsePattern/FalseTweaks/files/9664421/crash-2022-09-28_19.23.54-client.txt)
[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/9664422/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/FalsePattern/FalseTweaks/files/9664424/fml-junk-earlystartup.log)
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/9664425/latest.log)

**Comment by FalsePattern** [comment]
I managed to reproduce this locally, will be fixed in alpha 5.
