### ISSUE TITLE
IndexOutOfBoundsException while rendering items in GUI (idk why)

### ISSUE THREAD

**Issue by Asek3** [FalsePattern/FalseTweaks#45]
[crash-2022-09-28_19.17.54-client.txt](https://github.com/FalsePattern/FalseTweaks/files/9666013/crash-2022-09-28_19.17.54-client.txt)

**Comment by FalsePattern** [comment]
Workaround added for alpha 5, probably a misbehaving mod that's updating texture animations incorrectly.

**Comment by Asek3** [comment]
Probably fixed
