### ISSUE TITLE
lines in water cauldron

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalseTweaks#47]
mods list : 

00gasstation-mc1.7.10-0.3.5
falsepatternlib-mc1.7.10-0.10.11
falsetweaks-mc1.7.10-2.0.0-alpha0005

falsetweaks on

![Capture d’écran_2022-09-28_18-09-32](https://user-images.githubusercontent.com/42176772/193169807-81314dcc-633f-4200-af21-122395cd7a1c.png)

falsetweaks off

![Capture d’écran_2022-09-30_03-22-15](https://user-images.githubusercontent.com/42176772/193169809-95c88a5a-15fc-467a-abeb-f1a8945b1e10.png)

**Comment by FalsePattern** [comment]
Found the bug, the fix will be released in alpha 6

**Comment by quentin452** [comment]
fixed in 2.0 Alpha 6
