### ISSUE TITLE
Unable to read a class file correctly .minecraft/mods/falsepattern/org.joml-joml-1.10.5.jar

### ISSUE THREAD

**Issue by tyrael93** [FalsePattern/FalseTweaks#50]
Might as well reuse this one :smile: 

I deleted the falsepattern folder, but it's still spewing pagefuls of errors in the console about it can't read a class file correctly in joml.jar every time, which means it's an upstream problem.
There's no crash, but it's still an issue.

https://pastebin.com/C58dmsVM

**Comment by makamys** [comment]
If the dependency loader is not meant to ever load Forge mods, then this could be solved by adding all dependency jars to the loaded coremod list (`CoreModManager.getLoadedCoremods()`) to make the classpath mod discoverer skip over them.

**Comment by FalsePattern** [comment]
fixed in fplib, will be fixed in the startup optimizations module in alpha 6

**Comment by tyrael93** [comment]
The problem seems to be fixed. 

You can close the issue :+1:
