### ISSUE TITLE
The problem of weapon texture

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/FalseTweaks#53]
I found some unnatural places in the texture of weapons
![2022-10-01_14 03 30](https://user-images.githubusercontent.com/106000018/193395344-5359fb73-c82d-4b3c-9e87-807ed66b96d7.png)
![2022-10-01_14 03 19](https://user-images.githubusercontent.com/106000018/193395348-98551d4e-36ad-442b-b65f-19b63c6e3b4e.png)
![2022-10-01_14 03 23](https://user-images.githubusercontent.com/106000018/193395349-193045a5-c552-41e2-b404-03f3c6159eb1.png)

**Comment by FalsePattern** [comment]
i have no clue what the problem is, i don't see anywhing wrong
