### ISSUE TITLE
imconpat

### ISSUE THREAD

**Issue by iamsoNewBee** [FalsePattern/FalseTweaks#54]
[minecraft-exported-crash-info-2022-10-02T13-53-55.zip](https://github.com/FalsePattern/FalseTweaks/files/9691871/minecraft-exported-crash-info-2022-10-02T13-53-55.zip)
AND IT`S REALLY HARD TO FIND OUT WHICH EXACTLY LEAD TO THIS BUT FALSETWEAKS IS ONE OF THEM(BY THE WAY ,TRIANGULATOR DOESNT )

**Comment by FalsePattern** [comment]
There is something wrong with your internet, the FalsePatternLib library downloader cannot access the servers for some of the libraries required by FalseTweaks. Make sure that you can access this website: https://repo.maven.apache.org/, check your DNS or VPN settings.
![Screenshot_2022-10-02_13-55-38](https://user-images.githubusercontent.com/30945458/193452714-5b168a5c-36ad-47d1-bb96-469e6f871e58.png)

**Comment by iamsoNewBee** [comment]
oh, it`s nonpudate.

**Comment by FalsePattern** [comment]
yeah, all of my mods break if nonupdate is installed. I will probably add an update to FalsePatternLib that will force-disable nonupdate someday.

**Comment by iamsoNewBee** [comment]
good

**Comment by iamsoNewBee** [comment]
[crash-2022-10-02_20.05.54-client.txt](https://github.com/FalsePattern/FalseTweaks/files/9692437/crash-2022-10-02_20.05.54-client.txt)
lots of imcompat mods (those UE ones)

**Comment by FalsePattern** [comment]
Read.
![Screenshot_2022-10-02_14-09-39](https://user-images.githubusercontent.com/30945458/193453221-03312db6-30c3-41c7-9daa-8a2c893ae5d2.png)
