### ISSUE TITLE
TextureMap mixin crash

### ISSUE THREAD

**Issue by iamsoNewBee** [FalsePattern/FalseTweaks#57]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/98573273/193453372-c062b420-be87-44e1-9f86-6c6fab3611ba.png">
<img width="921" alt="image" src="https://user-images.githubusercontent.com/98573273/193453382-da19f054-0b3e-4b9e-b341-dd43d41402a0.png">
and they are real contributors
<img width="600" alt="image" src="https://user-images.githubusercontent.com/98573273/193453414-fdc82d3b-c354-4f9e-923c-c61e149d4315.png">
<img width="732" alt="image" src="https://user-images.githubusercontent.com/98573273/193453420-b726805e-5147-495b-b560-fac253b7ecd5.png">
<img width="861" alt="image" src="https://user-images.githubusercontent.com/98573273/193453425-e40d9687-5b3d-4202-870c-e9cde0913e0c.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/98573273/193453429-3bf19a46-fea9-4031-8698-78ff99e7b771.png">

**Comment by FalsePattern** [comment]
post the full `fml-client-latest.log` file, i can't do anything with just a useless crash report and modlist screenshots

**Comment by iamsoNewBee** [comment]
[minecraft-exported-crash-info-2022-10-02T20-06-04.zip](https://github.com/FalsePattern/FalseTweaks/files/9692452/minecraft-exported-crash-info-2022-10-02T20-06-04.zip)

**Comment by FalsePattern** [comment]
why do you have animfix installed? falsetweaks includes animfix

**Comment by FalsePattern** [comment]
![Screenshot_2022-10-02_14-19-11](https://user-images.githubusercontent.com/30945458/193453574-9cd6b0e3-316f-4507-b105-a000baaa5471.png)

**Comment by iamsoNewBee** [comment]
WOW IT`S IMPRESSIVE XD

**Comment by FalsePattern** [comment]
try removing animfix and see if the pack works then

**Comment by iamsoNewBee** [comment]
loading

**Comment by iamsoNewBee** [comment]
?game runs currently now without more crash.(it`s strange to change this title XD)
