### ISSUE TITLE
Z-fighting on spawn eggs and lether armor (again)

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#58]
https://user-images.githubusercontent.com/110309314/193457481-71ed3abf-2d63-4632-84a5-57230cee6e7e.mp4

**Comment by tyrael93** [comment]
Does that title also mean the Z-fighting stopped happening on weapons? I've had that issue on several modded weapons, but I've never tried checking spawn eggs and armor.

**Comment by kotmatross28729** [comment]
I don't know. Maybe

**Comment by tyrael93** [comment]
I'll test it myself and let you know in the issue then, to at least keep it on topic.
That aside, how did you manage to get full grass working (with what I can guess is optifine)? Falsetweaks completely breaks fullgrass compat for me.

**Comment by kotmatross28729** [comment]
> I'll test it myself and let you know in the issue then, to at least keep it on topic (Edit: **yes, there still is Z-fighting on weapons also**).
> 
> That aside, how did you manage to get full grass working (with what I can guess is optifine)? Falsetweaks completely breaks fullgrass compat for me.


Yes, I use optifine.
By the way, can I ask a question off topic?
When I play minecraft (with shaders), my PC just turns off after 5-10 minutes of playing, the time depends on the power limit set in the video card settings, I was told that the power supply is to blame, but it also happens in other games, but if the power limit set to less than 60%, then everything works fine, except for minecraft,
it passes absolutely all tests, on the load of the processor, video card, memory, and for some reason, it turns off only in games, can you please tell (if you understand what I mean) why the pc turns off in minecraft, even with 50% power limit and consumption no more than 100w (for this card the norm is 200+w)

**Comment by embeddedt** [comment]
> When I play minecraft (with shaders), my PC just turns off after 5-10 minutes of playing, the time depends on the power limit set in the video card settings, I was told that the power supply is to blame, but it also happens in other games, but if the power limit set to less than 60%, then everything works fine, except for minecraft,

Have you checked the temperatures? Most hardware will cut its own power if it gets too hot. Other games might not tax the GPU/CPU to the same degree so lowering the power limit is enough to keep the temperature down.

**Comment by kotmatross28729** [comment]
yes, the temperatures are even lower than in the same rdr2, in minecraft the processor temperature is 52°, the video card is 56-60°, while the limit is 83°

**Comment by FalsePattern** [comment]
Tweaked the hooks a bit, now it should work a bit more reliably.

**Comment by kotmatross28729** [comment]
> yes, the temperatures are even lower than in the same rdr2, in minecraft the processor temperature is 52°, the video card is 56-60°, while the limit is 83°

By the way, what is interesting is that it depends on the area (not confirmed, but there have been cases), that is, the chance that it will turn off on a regular field is less than in the most frequently turned off places - a dark forest and a bamboo forest (Biomes O Plenty), in a dark forest there are sun rays and reflections on the foliage, and in the bamboo forest there are a lot of foliage, falling leaves from bamboo (better foliage), sun rays (with them it turns off more often at sunrise or sunset) and + reflections on ... stones in the podzol ?
However, I can confirm that this is true, 9 out of 12 shutdowns happened in the bamboo forest, and the remaining 3 in the dark forest, and never in the mud or other small biomes

**Comment by kotmatross28729** [comment]
> Tweaked the hooks a bit in Beta 3, now it should work a bit more reliably.

I'll check now...

**Comment by kotmatross28729** [comment]
yes, it works, thanks!

**Comment by kotmatross28729** [comment]
> > When I play minecraft (with shaders), my PC just turns off after 5-10 minutes of playing, the time depends on the power limit set in the video card settings, I was told that the power supply is to blame, but it also happens in other games, but if the power limit set to less than 60%, then everything works fine, except for minecraft,
> 
> Have you checked the temperatures? Most hardware will cut its own power if it gets too hot. Other games might not tax the GPU/CPU to the same degree so lowering the power limit is enough to keep the temperature down.

or maybe minecraft is so demanding that my 700w power supply (which of course does not produce any 700) cannot properly supply the system?
I measured it with a multimeter and in minecraft the voltage is very unstable, usually 12.1, but at one moment it drops (maybe somewhere around 11.8, I don’t know, it turns off immediately)

**Comment by tyrael93** [comment]
I'm still getting some texture errors on all GT tools, just a different kind now. Now the tools have some very thin lines that make the item transparent here and there. Granted, it's less noticeable than the black garble on tools, but it's still there. 
I'll be able to provide a few images tomorrow.

**Comment by embeddedt** [comment]
It’s quite possible that your other PSU is simply faulty.

**Comment by kotmatross28729** [comment]
well, I don’t really think so, if it weren’t working properly, then it wouldn’t pass benchmarks (which it passes regardless of the power limit)
the problem was only in games, and it was solved by lowering the power limit, however, for each game it should be different, for example, in one game 75% is enough, and in another it will turn off even at 75, so it will need 60%, minecraft just was at the very bottom, and for him it was simply not enough to lower the frequency in just 1 program, so a very strong limitation to 110w, rather fixed this

**Comment by trollogyadherent** [comment]
ty for the copypasta

**Comment by kotmatross28729** [comment]
> Considering your cpu age is over 8 years, and your PSU has sagged well below 12v, and you're running an odd memory config 3x8gb perhaps, Im surprised your shit still boots. Your current system can run on a decent 500w psu. Free steps you should take: Update your drivers. Run a quick memtest. Make sure you're using the right memory channels of your motherboard, you can try running 1 or 2 sticks of memory for testing. Reseat your CPU, and reapply thermal compound, clean dust from pc if you haven't. Update motherboard bios. Check memory speeds in bios and compatibility with your current memory.
> 
> Money steps you could take: You could quadruple your MC fps by getting a cpu from this decade XD.

I use 8 + 16gb of memory, I have already tested it, it seems to be in order, and it is unlikely for everything else.
It started after changing the gpu to a more powerful one (even very) and here I assume that this is a power supply.
Yesterday I did a test - I removed all the restrictions on the power consumption of the gpu, set the forced speed of the gpu fans to 100%, and also overclocked.
As a result, he turned off as soon as I entered the world.

**Comment by kotmatross28729** [comment]
oh and by the way, it worked great on gtx 750ti which is much weaker than 3060ti, and I also have the cheapest power supply from aliexpress, and you rightly said that 500w can and will be enough for it, but it should be real 500w, without drawdowns, how does my power supply do it, which is allegedly at "700w" means a 1000w power supply should be enough.
Well, as for the processor, I simply don’t have money for a more expensive one than this one, because I can’t even buy a normal power supply, so with the processor I also have to change the motherboard, and I still have to mess around with wires, and indeed change mine " case" (it's just an iron box without ventilation, which has no lid, and of the ventilators there are only 2 fans on the video card, and there are also 7 dead flies that were electrocuted, and there is a 7mm layer of dust since the creation of this "case")
Well, if possible, do you know any normal xeon?
Well, which doesn’t matter how many cores, the main thing is that the frequency is good (as you know, all xeon processors don’t have this, well, maybe you just know some good one from this line?)

**Comment by Houstonruss** [comment]
what the fuck

**Comment by kotmatross28729** [comment]
what?

**Comment by kotmatross28729** [comment]
uh yeah

**Comment by kotmatross28729** [comment]
Well, it's actually not that bad, right?

**Comment by FalsePattern** [comment]
alright, fun's over, take this to dms or whatever
