### ISSUE TITLE
Strange artifacts due to triangulator

### ISSUE THREAD

**Issue by Serega007RU** [FalsePattern/FalseTweaks#59]
When FalseTweaks is installed, for some reason, such artifacts appear (see screenshots). Disabling the triangulator in the config solves this problem
![image](https://user-images.githubusercontent.com/64780091/194119507-61a7d96a-eac1-40d0-a2f2-4df6cadab4c6.png)

![image](https://user-images.githubusercontent.com/64780091/194120035-d4e35073-b674-4f44-9bd7-47710bde17a8.png)

[latest.log](https://github.com/FalsePattern/FalseTweaks/files/9717620/latest.log)

**Comment by Serega007RU** [comment]
It looks like it's a duplicate of #7, but it's marked as resolved, it looks like this problem has returned

**Comment by FalsePattern** [comment]
Cannot reproduce this bug on a clean local test instance, try disabling mods one by one until it goes away to find the cause.
