### ISSUE TITLE
[1.7.10] (partially fixed) Crash when i enable enableThreadedChunkUpdates from archaicfix + ENABLE_QUAD_TRIANGULATION from Falsetweaks

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalseTweaks#60]
This crash doesn't appear if falsetweaks or threadedchunkupdate is disabled
this crash doesn't appear with old version of falsetweaks

![Capture d’écran_2022-10-05_23-29-54](https://user-images.githubusercontent.com/42176772/194167620-8ecc458b-ca88-4651-922c-0b9203e6714a.png)

[crash-2022-10-05_23.17.20-client.txt](https://github.com/embeddedt/ArchaicFix/files/9719104/crash-2022-10-05_23.17.20-client.txt)

**Comment by quentin452** [comment]
crash caused by ENABLE_QUAD_TRIANGULATION=true in falsetweaks

**Comment by makamys** [comment]
> this crash doesn't appear with old version of falsetweaks

Can you say an exact version number?

**Comment by quentin452** [comment]
?

**Comment by quentin452** [comment]
> > this crash doesn't appear with old version of falsetweaks
> 
> Can you say an exact version number?

latest working version with  ENABLE_QUAD_TRIANGULATION=true and threaded chunk update is falsetweaks-mc1.7.10-2.0.0-alpha0006

**Comment by makamys** [comment]
Apparently there was a bug before alpha0007 that made triangulation always disabled (fixed in 07dcb22d52b806f6bff127560460e887c494e342), that's probably why the issue didn't appear then.

**Comment by quentin452** [comment]
ok

**Comment by makamys** [comment]
Did some testing and 2.0.0-alpha0001 is the last version that worked properly with triangulation and threaded chunk updating both enabled. (In alpha0002, TessellatorMixin doesn't even get applied, and in alpha0003 the bug that made triangulation always disabled was added).

**Comment by MagmaBro123** [comment]
Been quite a while, will this ever be fixed?

**Comment by quentin452** [comment]
it seem thats issue is fixed

**Comment by quentin452** [comment]
It seem that fixe the crash but i got an another issue when updating water
![Capture d’écran_2023-09-01_01-54-39](https://github.com/FalsePattern/FalseTweaks/assets/42176772/39da6029-0343-4037-9e4b-27da079ce907)

**Comment by FalsePattern** [comment]
No longer relevant, FalseTweaks now has its own threaded rendering.
