### ISSUE TITLE
[1.7.10] Sword glitch when i enable voxelizer in falsetweaks with archaicfix installed

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/FalseTweaks#61]
this bug doesn't appear with old version of falsetweaks
also bug with some other items

you can find the bug faster when using jetpack

mods list : 

archaicfix-mc1.7.10-0.3.3
falsepatternlib-mc1.7.10-0.10.13
falsetweaks-mc1.7.10-2.0.0-beta0003
SimplyJetpacks-MC1.7.10-1.5.3
00gasstation-mc1.7.10-0.3.5
CoFHCore-[1.7.10]3.1.4-329

vidéo : 

VOXELIZER=true edit: enableOcclusionTweaks=true,enableThreadedChunkUpdates=true

https://mega.nz/file/rsFhhBAC#x_t-6kcSrbCR2CC197sZL5jbS2J7ZZWfHBfMdRqNHXU

VOXELIZER=false edit: enableOcclusionTweaks=true,enableThreadedChunkUpdates=true

https://mega.nz/file/i5k1iBYA#ZqsRXqMiQrDtXEn0ukcNDxI8IUsKU2u6CfijNd2OwE8

**Comment by FalsePattern** [comment]
i don't see anything wrong in the voxelized version

**Comment by quentin452** [comment]
you need to enable enableOcclusionTweaks,enableThreadedChunkUpdates in archaicfix and VOXELIZER in falsetweaks to have this bug

**Comment by quentin452** [comment]
https://mega.nz/file/S5tjjbwK#KqSmBs_gXd1nFzmLVUniQvuTjNvubonIQuI-3okjr0k
I redid a video where you can see the bug better

**Comment by quentin452** [comment]
https://mega.nz/file/q4lBHTgA#5rpXd6Ai1g-KwctT5CJCDY9AV5HIDT5-SQBs-Z-6lBY

config you need to have the bug

**Comment by FalsePattern** [comment]
Does it also happen without the archaicfix occlusion tweaks?

**Comment by quentin452** [comment]
no , I can have the bug only with enableOcclusionTweaks+enableThreadedChunkUpdates and Voxelizer enabled

**Comment by quentin452** [comment]
it seem that issue get fixed
