### ISSUE TITLE
Strange terrain rendering

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/FalseTweaks#63]
![2022-10-09_21 46 33](https://user-images.githubusercontent.com/106000018/194760573-3cb7d06e-5668-4eb9-a8e1-71b3b3fea9d0.png)
![2022-10-09_21 46 42](https://user-images.githubusercontent.com/106000018/194760592-3b04885e-1802-4557-9065-f1a908fce9b4.png)

**Comment by FalsePattern** [comment]
Try turning off Anisotropic Filtering.

**Comment by quentin452** [comment]
do you have other mods installed?

**Comment by quentin452** [comment]
I don't see any flicker on the screen

**Comment by quentin452** [comment]
> > do you have other mods installed?
> 
> Yes

do you have archaicfix installed?

**Comment by Omgise** [comment]
Well, this problem has been solved with the update of GasStation mod :D
