### ISSUE TITLE
Ambient occlusion fix is broken

### ISSUE THREAD

**Issue by makamys** [FalsePattern/FalseTweaks#65]
## Old good
```
00gasstation-mc1.7.10-0.3.5.jar
falsepatternlib-mc1.7.10-0.10.13.jar
falsetweaks-mc1.7.10-2.0.0-alpha0006.jar
```
![](https://user-images.githubusercontent.com/13667520/195718799-1967ab5b-cbe6-4a2d-8560-8826b0b80d41.png)

## New bad
```
00gasstation-mc1.7.10-0.3.5.jar
falsepatternlib-mc1.7.10-0.10.13.jar
falsetweaks-mc1.7.10-2.0.0-{alpha0007 ~ beta0003}.jar
```
![](https://user-images.githubusercontent.com/13667520/195718811-b214e69b-1bbe-4f90-b5b7-ddf9e4ffa8c8.png)

**Comment by FalsePattern** [comment]
try calibrating again.

**Comment by makamys** [comment]
I just tried and I can reproduce it in a fresh instance.

* Added these mods:
    * `00gasstation-mc1.7.10-0.3.5.jar`
    * `falsepatternlib-mc1.7.10-0.10.13.jar`
    * `falsetweaks-mc1.7.10-2.0.0-beta0003.jar`
* Launched the game, calibrated, got the issue.
* Deleted `config` folder.
* Replaced `falsetweaks-mc1.7.10-2.0.0-beta0003.jar` with `falsetweaks-mc1.7.10-2.0.0-alpha0006.jar`
* Launched the game, calibrated, no issue.

**Comment by tyrael93** [comment]
So what's the verdict, just disable triangulator for the time being until it's fixed?

**Comment by FalsePattern** [comment]
try calibrating so that the images actually mismatch

**Comment by FalsePattern** [comment]
The issue has been found, it was a bug with the triangulation working in the opposite mode because of an oversight while refactoring. Should be fixed in the next release

**Comment by FalsePattern** [comment]
Closed as stale

**Comment by makamys** [comment]
Yes, it works fine now as of `2.0.2-hotfix1`.

I did some more testing to confirm what happened:

* In `2.0.0-beta3`, things actually work as expected when triangulation (`ENABLE_QUAD_TRIANGULATION`) is disabled. But when it's enabled, the diagonals are always oriented the wrong way. Changing `FLIP_DIAGONALS` has no effect. In my original report, I had triangulation enabled in all cases.

* `2.0.2-hotfix1` also works fine if triangulation is disabled. And when it's enabled, the diagonals are oriented the right way. Changing `FLIP_DIAGONALS` still has no effect.

As an aside, it might be a good idea to only show the configuration dialog when triangulation is disabled, since the setting has no effect otherwise, so it's kind of misleading.
