### ISSUE TITLE
Game not starting 

### ISSUE THREAD

**Issue by SegoItCh** [FalsePattern/FalseTweaks#66]
:C

**Comment by quentin452** [comment]
logs?

**Comment by SegoItCh** [comment]
No, it not even launch

**Comment by quentin452** [comment]
mods list

**Comment by SegoItCh** [comment]
Now it works, strange, triangulator-mc1.7.10-1.7.8 tho, says outdated in chat, could you update in curseforge?

**Comment by quentin452** [comment]
delete triangulator and animfix , and add falsetweaks (projects merged)

**Comment by SegoItCh** [comment]
It's falsetweaks for me in curseforge

**Comment by SegoItCh** [comment]
I suppose it's still triangulator by default because alpha/beta tag

**Comment by quentin452** [comment]
yes is falsetweaks on curseforge

**Comment by SegoItCh** [comment]
So game won't start w/o 00gasstation-mc1.7.10-0.3.5 and falsepatternlib-mc1.7.10-0.10.13, but I got no info about it on launch :/

**Comment by SegoItCh** [comment]
https://paste.gg/p/anonymous/f8c98484e57f476ca95fab391602066b
Getting this error for some reason with mod enabled
