### ISSUE TITLE
`TEXTURE_OPTIMIZATIONS` crashes with OptiFine+FastCraft+`-Dmixin.debug=true`

### ISSUE THREAD

**Issue by makamys** [FalsePattern/FalseTweaks#67]
The mod crashes on startup if all of the following are true:
* OptiFine is present
* FastCraft is present
* `TEXTURE_OPTIMIZATIONS` is enabled
* The `-Dmixin.debug=true` JVM flag is set

## Mod list

```
00gasstation-mc1.7.10-0.3.5.jar
falsepatternlib-mc1.7.10-0.10.13.jar
falsetweaks-mc1.7.10-2.0.0-beta0003.jar
fastcraft-1.23.jar
OptiFine_1.7.10_HD_U_D6.jar
```

## Crash log
[crash-2022-10-14_17.07.11-client.txt](https://github.com/FalsePattern/FalseTweaks/files/9787638/crash-2022-10-14_17.07.11-client.txt)

**Comment by tyrael93** [comment]
### **[A challenger appears!]**

I was wondering what was making my head scratch: the issue is this, I have the same setup (fast 23/fine D6/tweaks/lib all updated to the latest), minus gastweaks (using sponge 1.5) and texture optimization is enabled. 

The game doesn't crash, and in fact, runs quite well. Maybe give it a try with sponge mixins 1.5?

**Comment by makamys** [comment]
Oh, good catch. The issue doesn't appear in a fresh instance. It turns out it was happening because I had the `-Dmixin.debug=true` JVM flag set. I'd say it's still a valid issue though, just less pressing.

**Comment by FalsePattern** [comment]
Yep, i know what the issue is, mixin injection annotations have a separate non-debug and debug injection count value. I have some mixins set to a minimum of 0 for compat, but forgot to also set the debug value to 0.

**Comment by makamys** [comment]
The issue no longer happens with the latest versions of FalseTweaks, FPLib and GasStation.

## New mod list
```
00gasstation-mc1.7.10-0.5.1.jar
falsepatternlib-mc1.7.10-0.10.15.jar
falsetweaks-mc1.7.10-2.2.1.jar
fastcraft-1.23.jar
OptiFine_1.7.10_HD_U_D6.jar
```
