### ISSUE TITLE
 `TEXTURE_OPTIMIZATIONS` doesn't work with animated normal maps

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#70]
I already mentioned it once (or maybe not, I don't remember) that animated normal maps work "specially"
### IF: 

**`TEXTURE_OPTIMIZATIONS=true`,** pbr texture pack **on**

https://user-images.githubusercontent.com/110309314/200167372-f387a8a2-18e6-46cd-8d69-68ffb6e4d431.mp4

**`TEXTURE_OPTIMIZATIONS=false`,** pbr texture pack **on**

![2022-11-06_14 12 21](https://user-images.githubusercontent.com/110309314/200167425-d9c32c57-0c71-4743-9a43-c937601ef5fe.png)

**`TEXTURE_OPTIMIZATIONS=true`,** **normals **removed** from texture pack**

![2022-11-06_14 08 07](https://user-images.githubusercontent.com/110309314/200167467-c899e86a-b1c6-4a5a-a10d-1e56b883e397.png)

### **explanation**

**Here is a normal map  comparison of a sea lantern and sand (this is just an example, you can take any other blocks), here you can see that the sea lantern has an animated normal map, and this problem applies to any block that has an animated normal map**

block with animated normal map
![sea_lantern_n](https://user-images.githubusercontent.com/110309314/200167614-7b98d555-39fa-4baa-b6ff-eb7b3968a171.png)

simple block normal map
![sand_n](https://user-images.githubusercontent.com/110309314/200167618-65409462-1e96-4f6e-a527-91676508b6f1.png)

**Comment by FalsePattern** [comment]
Can you give me a link to this resource pack? I need to test this locally to fix it.

**Comment by kotmatross28729** [comment]
[§5AVPBR custom.zip](https://github.com/FalsePattern/FalseTweaks/files/10300007/5AVPBR.custom.zip)

**Comment by kotmatross28729** [comment]
And also need to install et futurum requiem for sea lantern or magma block i guess

**Comment by FalsePattern** [comment]
I tried fixing it, but it's not feasible and would require a full rewrite of the texture optimization logic. Added a note to the readme about it.
