### ISSUE TITLE
Z-fighting on spawn eggs and lether armor (again)

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/FalseTweaks#77]
https://user-images.githubusercontent.com/110309314/205997041-626a6c2c-5720-4ed3-b18d-c1b23f1d016d.mp4

**Comment by tyrael93** [comment]
Confirmed to also work with gregtech tools (The same issue as before).
![image](https://user-images.githubusercontent.com/5557920/206044435-3d921eb6-762c-410f-834c-8ebd3d9181c2.png)

**Comment by Natsukiw** [comment]
I also encountered the same problem, and configured forced_layers, it seems to have no effect?

**Comment by MagmaBro123** [comment]
Same issue.

**Comment by FalsePattern** [comment]
![Screenshot_2022-12-16_22-50-43](https://user-images.githubusercontent.com/30945458/208194906-8d4905c4-6456-4d07-a005-5836fb7974c6.png)
Fixed in 2.0.2

**Comment by kotmatross28729** [comment]
Oh thanks, It works now
