### ISSUE TITLE
Attempting to include False mods is hard. :(

### ISSUE THREAD

**Issue by Zilacon** [FalsePattern/FalseTweaks#79]
So i have a large modpack, around 337 mods. The performance and start up time is absolutely horrible.
So im always on the look out for fix mods and optimization mods to help in any way.

I have added gas station, falsepatternlib, and falsetweaks and have experienced many crashes since.

Ill upload all of the crash logs here, and a latest log file.
Any help trying to get your mods to work would be extremely appreciated!
[crash-2022-12-28_03.15.46-client.txt](https://github.com/FalsePattern/FalseTweaks/files/10314028/crash-2022-12-28_03.15.46-client.txt)
[crash-2022-12-28_03.31.27-client.txt](https://github.com/FalsePattern/FalseTweaks/files/10314031/crash-2022-12-28_03.31.27-client.txt)
[crash-2022-12-28_03.37.47-client.txt](https://github.com/FalsePattern/FalseTweaks/files/10314035/crash-2022-12-28_03.37.47-client.txt)
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/10314036/latest.log)

I had to remove the BetterLoadingScreen mod in order to get past the first 2 crashes. But kinda hit a wall once thaumcraft mods started crashing. Id like to keep using BetterLoadingScreen if possible.

Disabling things in the config just seems to get so far until another crash occurs requiring even more of the mod to be disabled.

**Comment by FalsePattern** [comment]
Disable the texture optimizations module

**Comment by Zilacon** [comment]
Same issue.
Instant crash.

[crash-2022-12-28_06.24.56-client.txt](https://github.com/FalsePattern/FalseTweaks/files/10314667/crash-2022-12-28_06.24.56-client.txt)
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/10314673/latest.log)

**Comment by FalsePattern** [comment]
Set `B:MIPMAP_FIX` to `false` inside the `00_modules` category in `falsetweaks.cfg`

**Comment by Zilacon** [comment]
I actually didnt do it incorrectly, you said "Texture Optimizations", nice edit btw.
Also it still doesnt work.
[crash-2022-12-28_06.41.20-client.txt](https://github.com/FalsePattern/FalseTweaks/files/10314745/crash-2022-12-28_06.41.20-client.txt)
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/10314746/latest.log)

**Comment by FalsePattern** [comment]
Rename the optifine jar from `[CLIENT]OptiFine_1.7.10_HD_U_E7.jar` to `OptiFine_1.7.10_HD_U_E7.jar`.
ALL of my mods are dependent on correctly detecting jar names. Any prefix before any mod names breaks my code.

**Comment by Zilacon** [comment]
That indeed solved the start up issues, awesome.
But now it freezes/deadlocks when joining a server after getting like 1-3 fps for about 5 seconds it just completely dies.
My average FPS on the server before was around 260 FPS so thats extremely low.
I have 10GB of ram allocated.
Any ideas?

[latest.log](https://github.com/FalsePattern/FalseTweaks/files/10314809/latest.log)

**Comment by FalsePattern** [comment]
No idea.
