### ISSUE TITLE
Triangulator still mentioned

### ISSUE THREAD

**Issue by Temeraro** [FalsePattern/FalseTweaks#80]
![4d3aef0162ad06a1309f9860493c9731](https://user-images.githubusercontent.com/121085818/210410921-0983276e-b64c-434b-be52-fe01972ec113.png)

Minor. Triangulator still mentioned if FalseTweaks has not yet been calibrated. Could cause confusion if someone is unaware of previous name.

**Comment by couleurm** [comment]
or atleast add something like [FalseTweaks] at the start of the string to indicate what mod is manifesting this warning

**Comment by FalsePattern** [comment]
> or atleast add something like [FalseTweaks] at the start of the string to indicate what mod is manifesting this warning

fixed since 2.1.0 https://github.com/FalsePattern/FalseTweaks/commit/1e49cd5b23fb24b6bad72bf7ae05cf744521352e
