### ISSUE TITLE
falsetweaks causes opengl error 1282 + items not showing up in buildcraft pipes

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#81]
if you have buildcraft and falsetweaks installed, then when transporting items between mechanisms (for example, a chest), the items will disappear and will not be displayed in pipes, also if nei is installed, then there will be a lot of spam in the chat

### with false tweaks

https://user-images.githubusercontent.com/122032896/210806769-f3f89e55-a50d-4fac-bf47-16cf16da91e7.mp4

### without false tweaks

https://user-images.githubusercontent.com/122032896/210806213-b5a29dd3-4635-40b0-97d0-484b9613f48f.mp4

## how to reproduce:
1.connect 2 chests with transport pipes
2.put any ITEM (NOT a BLOCK) in one chest
3.start the generator
4.get error

## mod list:
00gasstation-mc1.7.10-0.5.1.jar
falsepatternlib-mc1.7.10-0.10.14.jar
falsetweaks-mc1.7.10-2.0.2-hotfix1.jar
OptiFine_1.7.10_HD_U_E7.jar
buildcraft-7.1.25.jar

**Comment by FalsePattern** [comment]
Works in 3.5.1
