### ISSUE TITLE
Version 2.1.0 starts the game normally, and version 2.2.0 crashes at startup

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/FalseTweaks#84]
[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/10369797/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/FalsePattern/FalseTweaks/files/10369798/fml-junk-earlystartup.log)
[latest.log](https://github.com/FalsePattern/FalseTweaks/files/10369799/latest.log)

**Comment by jrslwaw** [comment]
crash due to hodgepodge
falsepattern added new feature ADVANCED_PROFILER just disable it
he is probably will fix it

**Comment by FalsePattern** [comment]
Duplicate of #85
