### ISSUE TITLE
crash immediately after loading 2.20

### ISSUE THREAD

**Issue by iamsoNewBee** [FalsePattern/FalseTweaks#86]
[minecraft-exported-crash-info-2023-01-09T23-04-42.zip](https://github.com/FalsePattern/FalseTweaks/files/10374257/minecraft-exported-crash-info-2023-01-09T23-04-42.zip)
 

it seems that everyone is reporting this. eh..

**Comment by FalsePattern** [comment]
Duplicate of #85
