### ISSUE TITLE
Your Update Checker is broken. The latest release says its outdated.

### ISSUE THREAD

**Issue by MagmaBro123** [FalsePattern/FalseTweaks#89]
Title.

The latest release (https://github.com/FalsePattern/FalseTweaks/releases) was posted Yesterday. Not sure what's going on.

![2023-01-10_10 39 25](https://user-images.githubusercontent.com/51277766/211623264-34df8920-63cf-4597-8a70-c6d58b92278d.png)

**Comment by FalsePattern** [comment]
fixed
