### ISSUE TITLE
Voxelizer item rendering issue with Thermal Foundation buckets

### ISSUE THREAD

**Issue by AstroTibs** [FalsePattern/FalseTweaks#91]
Hi, I've got a simple issue.

I noticed that with `B:VOXELIZER=true`, the bucket items from _Thermal Foundation_ do not render correctly in-hand or as entity items. They only render correctly in-inventory.

![2023-02-01_17 46 59](https://user-images.githubusercontent.com/29684118/216193808-acb0aee1-b1fe-4e82-9f2a-e2adca49254f.png)

All the TF buckets are multi-frame animations, using an mcmeta file similar to the following:

```
{
  "animation": {
    "frametime": 4
  }
}
```

The new Blaze Powder animation from TF is also bugged, but is just missing its spine texture.

The animated Biome Radar from _Biomes o' Plenty_ seems to be unaffected, indicating that it does not affect all animated textures.

**Comment by FalsePattern** [comment]
Fixed in 2.3.1
