### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by MrSliTraP2716Lua** [FalsePattern/FalseTweaks#94]
java.lang.NoClassDefFoundError: net/minecraft/client/settings/GameSettings - Crash on Start Stady in TLauncher Legacy The Launcher

Current Used Mods List:
UniMixins_all-0.1.5_best.jar (all)
ArchaicFix-0.5.0_conflicted-with-CoFH.jar (conflicted without UniMixins)
CoFH_Core-3.1.4-329.jar
CoFH_Lib-1.2.1-185.jar
EtFutuRumReQuiem-2.4.3+_fork.jar (mixin cutted)
FalsePattern_Lib-0.10.15.jar
FalseTweaks-2.2.1.jar

**Comment by MrSliTraP2716Lua** [comment]
[crash-2023-03-14_11.14.29-client.txt](https://github.com/FalsePattern/FalseTweaks/files/10967105/crash-2023-03-14_11.14.29-client.txt)

**Comment by Pilzinsel64** [comment]
Same for me. I guess it's because unimixins. A nonmixin-build would be nice! :)
