### ISSUE TITLE
Weird rendering on connected textures from Hbm's Nuclear Tech Mod

### ISSUE THREAD

**Issue by funnyman8** [FalsePattern/FalseTweaks#96]
With the mod:
![javaw_t4R5PdwPc4](https://user-images.githubusercontent.com/97941003/226198777-2b6190ed-4fc3-4c95-bf6b-fe8fc8850026.png)

Without the mod:
![javaw_gBqAWSpbtL](https://user-images.githubusercontent.com/97941003/226198789-5efc385c-79f5-46f6-a2eb-02c32b9f985b.png)

Issue likely stems from the triangulator combined with NTM's own rendering for connected texture blocks, NTM is open source and the connected texture-related rendering is all found here: https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/tree/master/src/main/java/com/hbm/render/block/ct

**Comment by DarianLStephens** [comment]
Was a solution to this ever discovered?
With the release of the NTM Space fork, I'm planning to run it on my server with friends, but losing FalseTweaks would be a big blow.

**Comment by DarianLStephens** [comment]
I don't know if it helps, but it looks like this now:
![2024-08-12_02 57 27](https://github.com/user-attachments/assets/ca871ceb-b397-4603-8153-0d9bd98f0c1c)

**Comment by FalsePattern** [comment]
Try turning off the triangulator module and see if that fixes it.

**Comment by FalsePattern** [comment]
Also try adding `com.hbm.render.block.*` to the `TESSELLATOR_USE_REPLACEMENT_TARGETS` list in falsetweaks.cfg

**Comment by FalsePattern** [comment]
I built a jar with some patches that i tested against NTM 1.0.27_X5027, please check if this works:
https://mvn.falsepattern.com/releases/com/falsepattern/falsetweaks-mc1.7.10/3.1.0-4-gb80d5fc/falsetweaks-mc1.7.10-3.1.0-4-gb80d5fc.jar

**Comment by DarianLStephens** [comment]
Sorry, I only just woke up.
I see that the Modrinth version was updated after you sent this, does that include the fixes?

I haven't tried it yet, but quad triangulation seemed to be off by default (ENABLE_QUAD_TRIANGULATION).
If the new version doesn't work, I'll try the tesselator target thing.

**Comment by FalsePattern** [comment]
Fixed in 3.x
