### ISSUE TITLE
The game crashed on startup

### ISSUE THREAD

**Issue by Omgise** [FalsePattern/FalseTweaks#97]
[fml-client-latest.log](https://github.com/FalsePattern/FalseTweaks/files/11183367/fml-client-latest.log)

**Comment by FalsePattern** [comment]
Fixed in FalsePatternLib 0.11.2

**Comment by Omgise** [comment]
> Fixed in FalsePatternLib 0.11.2

Yes, the crash was fixed, thanks! :p
