### ISSUE TITLE
Hey, 1.7.10 PvPer here

### ISSUE THREAD

**Issue by couleurm** [FalsePattern/FalseTweaks#98]
Hey I use your 1.7.10 mods to PvP, it's a [rare sight these days](https://howoldisminecraft1710.today/) to see necro-modders 

(never even knew the term before I read the [gist](https://gist.github.com/makamys/7cb74cd71d93a4332d2891db2624e17c))

I failed to find any of your socials (I imagine this is intentional), where could we have a chat?

**Comment by FalsePattern** [comment]
you can contact me through my anonymized email address, i enabled it on my github profile.
