### ISSUE TITLE
Incompatibility when used together with lwjgl3ify with other mods

### ISSUE THREAD

**Issue by Darek505** [FalsePattern/FalseTweaks#99]
This mod (at least since the latest versions) can run with lwjgl3ify alone, but when certain mods are added, it crashes.

Here is a list of mods with their stacktraces that crash when using lwjgl3ify and falsetweaks:
https://pastebin.com/vxJtwZAg

(This is definitely related to falsetweaks, because if I remove it, then lwjgl3ify can start with these mods, and when I add falsetweaks , I get these crashes)

**Comment by oneechanhax** [comment]
Unsure if this is related, GT;NH 2.4.0 with lwjgl3ify for Java 20, is crashing with mixin re-entry errors. 
No java expert and i dont code java ever. It appears like they are conflicting on a mixin however trying  to disable features in falsetweaks and FastCraft doesnt appear to change anything about the crash. 
Using Falselib for the multithreading mod and everything loads fine. My GTNH is a little more modded than others with some QOL and perf mods but nothing conflicts except this. Loads when mod is disabled.

Feel free to ask questions or ask for different senarios, not a java dev but I can C++ pretty well and use linux so i am versed in dev work. 

Crash
https://pastebin.com/jkUUFtzm

Modlist
https://pastebin.com/eHbf9sTy

**Comment by Crimento** [comment]
Just tried this on clean install of just FalseTweaks and LWJGL3ify along with required libs, same result

https://mclo.gs/uQR5v6L

**Comment by FalsePattern** [comment]
Fixed in 2.7.0 Preview 4 + FalsePatternLib 1.0.0 Preview 3

**Comment by Darek505** [comment]
well, on the one hand this is fixed, in that it doesn’t crash on startup, but on the other hand, the world is not rendered at all + items have no textures (**looks like** a bug like with intel or something similar):


https://github.com/FalsePattern/FalseTweaks/assets/122032896/29da4cae-bc97-48f8-9414-f1e6582aa86d



Mods:
+unimixins-all-1.7.10-0.1.14
falsepatternlib-mc1.7.10-1.0.0-pre03
falsetweaks-mc1.7.10-2.7.0-pre04
lwjgl3ify-1.5.4


~~in fact, this this has nothing to do with this problem, because this report talks specifically about the crash, and it has been fixed, but if we talk about the general compatibility between falsetweaks and lwjgl3ify , then the bug still exists~~

**Comment by FalsePattern** [comment]
2.7.0 should work now, make sure to delete falsetweaks.cfg and let it regenerate with default settings.

I have tested it on:
- Linux
- AMD Mesa drivers 23.1.9
- Lwjgl3ify 1.5.4
- Java 21

**Comment by Darek505** [comment]
I tried deleting falsetweaks.cfg, it didn't help.
tested it on:

+ Windows 10

+ Nvidia 2060 - 546.17

+ Lwjgl3ify 1.5.4

+ Java (jdk) 21.0.1

falsepatternlib - 1.0.0 Preview 3
falsetweaks - 2.7.0
unimixins - all-0.1.14

installed via PrismLauncher (lwjgl3ify-1.5.4-multimc.zip)

no error if there is no falsetweaks

**Comment by FalsePattern** [comment]
Hmmm... try setting `TEXTURE_OPTIMIZATIONS` to `false` in the falsetweaks config and see if that does anything

**Comment by Crimento** [comment]
@FalsePattern can confirm, disabling texture optimization helped. With it same thing happening with LWJGL3 (Win 11, RTX2070S@536.99, Liberica JDK 20)

![image](https://github.com/FalsePattern/FalseTweaks/assets/8221822/1d19c6b6-f129-40dd-94e2-d41a1f4a90a6)

partly related, seems like GTNH team is also working on multi-threaded renderer, you may want to take a look
https://github.com/GTNewHorizons/Angelica/tree/the-mergening-sodium
